In [83]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')

# Write query to get date, tmax, and tmin from weather
query = """
SELECT *
  FROM bronze.raw_fintech_data;
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [74]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')

# Write query to get date, tmax, and tmin from weather
query = """
SELECT *
  FROM silver.stg_customers;
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [99]:
a['last_login_date']

0       2025-12-23
1       2025-08-16
2         20251102
3       2025-06-24
4       17/03/2026
           ...
5095    2026-03-17
5096    2025-09-09
5097    2026-04-30
5098    2025-09-21
5099    04/08/2025
Name: last_login_date, Length: 5100, dtype: str

In [77]:
df['gender'].unique()

<ArrowStringArray>
['M', 'Other', 'null', 'F', '', nan, 'N/A', 'NA']
Length: 8, dtype: str

In [70]:
sorted(b.columns)

['address',
 'avg_monthly_logins',
 'bankruptcy_flag',
 'city',
 'country',
 'credit_score',
 'credit_total_limit',
 'credit_total_used',
 'credit_utilization_pct',
 'customer_id',
 'customer_segment',
 'date_of_birth',
 'email',
 'first_name',
 'gender',
 'inquiries_6m',
 'kyc_status',
 'last_login_date',
 'last_name',
 'lat',
 'late_payments_12m',
 'load_timestamp',
 'lon',
 'mobile_app_registered',
 'nationality',
 'num_credit_accounts',
 'oldest_account_age_months',
 'paperless_statements',
 'phone_number',
 'preferred_channel',
 'push_notifications',
 'registration_date',
 'relationship_manager',
 'risk_score',
 'status',
 'web_banking_registered']

In [71]:
sorted(a.columns)

['accounts',
 'address',
 'city',
 'country',
 'credit_info.bankruptcy_flag',
 'credit_info.credit_score',
 'credit_info.currency',
 'credit_info.inquiries_6m',
 'credit_info.late_payments_12m',
 'credit_info.num_credit_accounts',
 'credit_info.oldest_account_age_months',
 'credit_info.total_limit',
 'credit_info.total_used',
 'credit_info.utilization_pct',
 'customer_id',
 'customer_segment',
 'date_of_birth',
 'digital_engagement.avg_monthly_logins',
 'digital_engagement.last_login_date',
 'digital_engagement.mobile_app_registered',
 'digital_engagement.paperless_statements',
 'digital_engagement.preferred_channel',
 'digital_engagement.push_notifications',
 'digital_engagement.web_banking_registered',
 'email',
 'first_name',
 'gender',
 'kyc_status',
 'last_name',
 'lat',
 'loans',
 'lon',
 'nationality',
 'phone_number',
 'registration_date',
 'relationship_manager',
 'risk_score',
 'status',
 'transactions']

In [56]:
pd.json_normalize(df['data']).columns

Index(['lat', 'lon', 'city', 'email', 'loans', 'gender', 'status', 'address',
       'country', 'accounts', 'last_name', 'first_name', 'kyc_status',
       'risk_score', 'customer_id', 'nationality', 'phone_number',
       'transactions', 'date_of_birth', 'customer_segment',
       'registration_date', 'relationship_manager', 'credit_info.currency',
       'credit_info.total_used', 'credit_info.total_limit',
       'credit_info.credit_score', 'credit_info.inquiries_6m',
       'credit_info.bankruptcy_flag', 'credit_info.utilization_pct',
       'credit_info.late_payments_12m', 'credit_info.num_credit_accounts',
       'credit_info.oldest_account_age_months',
       'digital_engagement.last_login_date',
       'digital_engagement.preferred_channel',
       'digital_engagement.avg_monthly_logins',
       'digital_engagement.push_notifications',
       'digital_engagement.paperless_statements',
       'digital_engagement.mobile_app_registered',
       'digital_engagement.web_banking_registered'],
      dtype='str')

# Exploración

In [21]:
df_exploded = pd.json_normalize(
    df['data'], 
    record_path=['transactions'], 
    meta=['customer_id']
)

In [9]:
data = pd.json_normalize(df['data'].values)

In [195]:
data.head(3)

,lat,lon,city,email,loans,gender,status,address,country,accounts,...,credit_info.late_payments_12m,credit_info.num_credit_accounts,credit_info.oldest_account_age_months,digital_engagement.last_login_date,digital_engagement.preferred_channel,digital_engagement.avg_monthly_logins,digital_engagement.push_notifications,digital_engagement.paperless_statements,digital_engagement.mobile_app_registered,digital_engagement.web_banking_registered
0,-18.551408,-69.638686,La Serna,lucas.brito@gmail.com,"[{'type': 'business', 'status': 'default', 'lo...",F,suspended,"Pasaje Bolivia 637 Interior 460, Nueva Côte d'...",CL,"[{'status': 'frozen', 'balance': 292109.25, 'c...",...,7,2,242,2025-12-23,phone,60,False,True,True,False
1,-4.476765,-68.027337,Salvador,oliver.montalbán@bol.com.br,"[{'type': 'education', 'status': 'paid_off', '...",M,inactive,"Av. carrera 5ª # 12-48 Sur, Casa 55, 054138, R...",BR,"[{'status': 'closed', 'balance': 405626.68, 'c...",...,3,6,40,2025-08-16,branch,20,False,True,False,True
2,8.009853,-73.370236,Medellin,matilda.olivé@gmail.com,"[{'type': 'education', 'status': 'delinquent',...",Other,suspended,"Dg. 9U # 6-8 Sur, Bodega 108, 258646, Tocancip...",CO,"[{'status': 'closed', 'balance': 271756.62, 'c...",...,8,1,271,20251102,phone,39,True,True,True,False

In [17]:
loan = pd.json_normalize(data['loans'].explode())

In [24]:
pd.Series(loan['principal'].unique()).to_csv("temp.csv")

In [196]:
len(data)

5100

In [197]:
df_duplicated = data[data['customer_id'].duplicated()]
len(df_duplicated)

100

In [198]:
data = data[~data['customer_id'].duplicated()]

In [199]:
data.isnull().sum().sort_values(ascending=False)

relationship_manager                         111
address                                       78
digital_engagement.avg_monthly_logins         68
gender                                        47
city                                           0
lon                                            0
lat                                            0
status                                         0
loans                                          0
email                                          0
accounts                                       0
first_name                                     0
kyc_status                                     0
risk_score                                     0
country                                        0
customer_id                                    0
nationality                                    0
transactions                                   0
phone_number                                   0
date_of_birth                                  0
customer_segment                               0
registration_date                              0
last_name                                      0
credit_info.currency                           0
credit_info.total_used                         0
credit_info.credit_score                       0
credit_info.total_limit                        0
credit_info.bankruptcy_flag                    0
credit_info.utilization_pct                    0
credit_info.late_payments_12m                  0
credit_info.inquiries_6m                       0
credit_info.num_credit_accounts                0
credit_info.oldest_account_age_months          0
digital_engagement.last_login_date             0
digital_engagement.preferred_channel           0
digital_engagement.push_notifications          0
digital_engagement.paperless_statements        0
digital_engagement.mobile_app_registered       0
digital_engagement.web_banking_registered      0
dtype: int64

In [200]:
data['digital_engagement.avg_monthly_logins'].unique()

array([60, 20, 39, 6, 57, 35, 44, 12, 45, 3, 22, 53, 40, 52, 41, 1, 7, 13,
       55, 11, 23, 9, 56, 46, 16, 50, 18, 21, 5, 30, 27, 'null', 49, None,
       59, 2, 4, 26, 25, 58, 0, 38, 'N/A', 8, 28, 43, 24, 36, 51, 33, 17,
       47, 'NA', 48, 19, 34, 42, 10, 15, 29, 54, 32, '', 14, 37, 31],
      dtype=object)

In [201]:
missing_values = ['NA', 'N/A', 'null', 'nan', '',' ', None]

In [202]:

for col in data.columns:
    if data[col].isin(missing_values).any():
        print(col)

gender
address
relationship_manager
digital_engagement.avg_monthly_logins

# Reporte de Valores Nulos

| Variable | Nulos |
| :--- | :---: |
| relationship_manager | 111 |
| address | 78 |
| avg_monthly_logins | 68 |
| gender | 47 |

## relationship_manager

In [203]:
data['relationship_manager'].unique()

<StringArray>
[  'Luis Hernandez',      'Sofia Lopez', 'Valentina Torres',
     'Ana Martinez',  'Nicolas Mendoza',               'NA',
    'Daniela Rojas',     'Lucia Ortega',   'Alejandro Diaz',
   'Andres Morales',                nan,     'Maria Garcia',
     'Camila Reyes',  'Isabella Vargas', 'Sebastian Castro',
 'Carlos Rodriguez',             'null',    'Diego Ramirez',
              'N/A',                 '']
Length: 20, dtype: str

In [204]:
missing_values = ['NA', 'N/A', 'null', 'nan', '', None]

data['relationship_manager'] = (
    data['relationship_manager']
    .replace(missing_values, np.nan)
)

In [205]:
data['relationship_manager'].unique()

<StringArray>
[  'Luis Hernandez',      'Sofia Lopez', 'Valentina Torres',
     'Ana Martinez',  'Nicolas Mendoza',                nan,
    'Daniela Rojas',     'Lucia Ortega',   'Alejandro Diaz',
   'Andres Morales',     'Maria Garcia',     'Camila Reyes',
  'Isabella Vargas', 'Sebastian Castro', 'Carlos Rodriguez',
    'Diego Ramirez']
Length: 16, dtype: str

## address

In [206]:
data['address'][data['address'].isin(missing_values)].unique()

<StringArray>
['NA', 'null', '', 'N/A', nan]
Length: 5, dtype: str

In [207]:
data['address'] = (
    data['address']
    .replace(missing_values, np.nan)
)

In [208]:
data['address'][data['address'].isin(missing_values)].unique()

<StringArray>
[nan]
Length: 1, dtype: str

## digital_engagement.avg_monthly_logins

In [209]:
data['digital_engagement.avg_monthly_logins'].unique()

array([60, 20, 39, 6, 57, 35, 44, 12, 45, 3, 22, 53, 40, 52, 41, 1, 7, 13,
       55, 11, 23, 9, 56, 46, 16, 50, 18, 21, 5, 30, 27, 'null', 49, None,
       59, 2, 4, 26, 25, 58, 0, 38, 'N/A', 8, 28, 43, 24, 36, 51, 33, 17,
       47, 'NA', 48, 19, 34, 42, 10, 15, 29, 54, 32, '', 14, 37, 31],
      dtype=object)

In [210]:
data['digital_engagement.avg_monthly_logins'] = (
    data['digital_engagement.avg_monthly_logins']
    .replace(missing_values, np.nan)
)

In [211]:
data['digital_engagement.avg_monthly_logins'].unique()

array([60, 20, 39, 6, 57, 35, 44, 12, 45, 3, 22, 53, 40, 52, 41, 1, 7, 13,
       55, 11, 23, 9, 56, 46, 16, 50, 18, 21, 5, 30, 27, nan, 49, 59, 2,
       4, 26, 25, 58, 0, 38, 8, 28, 43, 24, 36, 51, 33, 17, 47, 48, 19,
       34, 42, 10, 15, 29, 54, 32, 14, 37, 31], dtype=object)

## gender

In [212]:
data['gender'].unique()

<StringArray>
['F', 'M', 'Other', '', 'N/A', 'null', 'NA', nan]
Length: 8, dtype: str

In [213]:
data['gender'] = (
    data['gender']
    .replace(missing_values, np.nan)
)

In [214]:
data['gender'].unique()

<StringArray>
['F', 'M', 'Other', nan]
Length: 4, dtype: str

## Reading again the count of null values

In [215]:
data.isnull().sum().sort_values(ascending=False)

relationship_manager                         496
address                                      393
digital_engagement.avg_monthly_logins        374
gender                                       271
city                                           0
lon                                            0
lat                                            0
status                                         0
loans                                          0
email                                          0
accounts                                       0
first_name                                     0
kyc_status                                     0
risk_score                                     0
country                                        0
customer_id                                    0
nationality                                    0
transactions                                   0
phone_number                                   0
date_of_birth                                  0
customer_segment                               0
registration_date                              0
last_name                                      0
credit_info.currency                           0
credit_info.total_used                         0
credit_info.credit_score                       0
credit_info.total_limit                        0
credit_info.bankruptcy_flag                    0
credit_info.utilization_pct                    0
credit_info.late_payments_12m                  0
credit_info.inquiries_6m                       0
credit_info.num_credit_accounts                0
credit_info.oldest_account_age_months          0
digital_engagement.last_login_date             0
digital_engagement.preferred_channel           0
digital_engagement.push_notifications          0
digital_engagement.paperless_statements        0
digital_engagement.mobile_app_registered       0
digital_engagement.web_banking_registered      0
dtype: int64

# Revisión cada columna

In [216]:
pd.json_normalize(df['data']).columns

Index(['lat', 'lon', 'city', 'email', 'loans', 'gender', 'status', 'address',
       'country', 'accounts', 'last_name', 'first_name', 'kyc_status',
       'risk_score', 'customer_id', 'nationality', 'phone_number',
       'transactions', 'date_of_birth', 'customer_segment',
       'registration_date', 'relationship_manager', 'credit_info.currency',
       'credit_info.total_used', 'credit_info.total_limit',
       'credit_info.credit_score', 'credit_info.inquiries_6m',
       'credit_info.bankruptcy_flag', 'credit_info.utilization_pct',
       'credit_info.late_payments_12m', 'credit_info.num_credit_accounts',
       'credit_info.oldest_account_age_months',
       'digital_engagement.last_login_date',
       'digital_engagement.preferred_channel',
       'digital_engagement.avg_monthly_logins',
       'digital_engagement.push_notifications',
       'digital_engagement.paperless_statements',
       'digital_engagement.mobile_app_registered',
       'digital_engagement.web_banking_registered'],
      dtype='str')

In [217]:
import pandas as pd

def validar_coordenadas(df):
    # 1. Verificar valores nulos
    nulos_lat = df['lat'].isnull().sum()
    nulos_lon = df['lon'].isnull().sum()
    
    # 2. Definir rangos válidos
    # Latitud: -90 a 90 | Longitud: -180 a 180
    fuera_rango = df[
        (df['lat'] < -90) | (df['lat'] > 90) | 
        (df['lon'] < -180) | (df['lon'] > 180)
    ]
    
    print("--- Reporte de Validación ---")
    print(f"Valores nulos en Latitud: {nulos_lat}")
    print(f"Valores nulos en Longitud: {nulos_lon}")
    print(f"Registros fuera de rango geográfico: {len(fuera_rango)}")
    
    if not fuera_rango.empty:
        print("\nEjemplos de datos erróneos:")
        print(fuera_rango[['lat', 'lon']].head())
    else:
        print("\n✅ Todos los valores están dentro de los rangos lógicos.")
    return fuera_rango

# Ejecución
fuera = validar_coordenadas(data)

--- Reporte de Validación ---
Valores nulos en Latitud: 0
Valores nulos en Longitud: 0
Registros fuera de rango geográfico: 340

Ejemplos de datos erróneos:
           lat         lon
38   43.213416  276.536473
41 -133.848080  -71.792598
53  140.816197 -378.344231
70 -195.174113  361.343921
92 -139.702335  320.180553

## lat lon

In [218]:
def validate_coords(df):
    lat_bad = ~df['lat'].between(-90, 90)
    lon_bad = ~df['lon'].between(-180, 180)

    df['geo_valid'] = ~(lat_bad | lon_bad)

    return df
validate_coords(data)[validate_coords(data)['geo_valid'] == False]

,lat,lon,city,email,loans,gender,status,address,country,accounts,...,credit_info.num_credit_accounts,credit_info.oldest_account_age_months,digital_engagement.last_login_date,digital_engagement.preferred_channel,digital_engagement.avg_monthly_logins,digital_engagement.push_notifications,digital_engagement.paperless_statements,digital_engagement.mobile_app_registered,digital_engagement.web_banking_registered,geo_valid
38,43.213416,276.536473,Mendoza,ocampo.gomez@hotmail.com,"[{'type': 'education', 'status': 'paid_off', '...",Other,Cerrado,"Calzada Ledesma 313 097, San Eugenia los altos...",AR,"[{'status': 'closed', 'balance': 116275261.94,...",...,10,43,2025-12-05,branch,27,True,False,False,False,False
41,-133.848080,-71.792598,Buenos Aires,damián.ramos@gmail.com,"[{'type': 'personal', 'status': 'default', 'lo...",M,inactive,"Circuito Sur Olivo 135 876, San Jorge los bajo...",AR,"[{'status': 'frozen', 'balance': '237661.44 US...",...,2,116,03/02/2026,atm,22,yes,True,True,True,False
53,140.816197,-378.344231,Barranquilla,elkin.pastor@hotmail.com,"[{'type': 'auto', 'status': 'default', 'loan_i...",M,inactive,"Av. Neuquén N° 31 Local 97, Comodoro Rivadavia...",CO,"[{'status': 'closed', 'balance': 285806.07, 'c...",...,2,117,2025-08-11,branch,52,True,False,True,False,False
70,-195.174113,361.343921,Buenos Aires,cristina.véliz@gmail.com,[],NaN,active,"Pasaje Norte Candelaria 568 276, San Alfredo l...",AR,"[{'status': 'closed', 'balance': 415463.37, 'c...",...,2,52,2025-08-24,atm,52,True,True,False,True,False
92,-139.702335,320.180553,Lima,nilo.gonzalez@hotmail.com,[],M,suspended,"Continuación Sur Zambrano 860 047, San José Ma...",PE,"[{'status': 'active', 'balance': 142479.13, 'c...",...,2,175,2025-06-21,branch,57,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5058,-177.699488,-183.580501,Rio de Janeiro,lucía.rodrigues@yahoo.com.br..,"[{'type': 'auto', 'status': 'paid_off', 'loan_...",M,activo,"Blv. Rosario N° 66 Piso 3 Dto. 2, Viedma 8500,...",BR,"[{'status': 'closed', 'balance': 352690.34, 'c...",...,5,250,2025-05-15,atm,9,False,False,False,False,False
5061,160.844099,228.042959,Montevideo,aurelio.nava@hotmail.com,[],Other,active,"Calle Irán 620 Edif. 986 , Depto. 970, Vieja C...",UY,"[{'status': 'active', 'balance': 182535.11, 'c...",...,10,345,2025-06-25,web,47,True,False,True,True,False
5063,191.256381,29.415876,Paysandu,maría.lara@hotmail.com,"[{'type': 'personal', 'status': 'default', 'lo...",NaN,inactive,NaN,UY,"[{'status': 'closed', 'balance': 3964170.77, '...",...,7,113,05/07/2025,branch,39,True,True,False,False,False
5076,-144.065031,374.347711,Paysandu,ángela.cavalcanti@yahoo.com,"[{'type': 'personal', 'status': 'default', 'lo...",NaN,inactive,"Glorieta de Leandro Font 681 Apt. 15 , Girona,...",UY,"[{'status': 'active', 'balance': '16787556.91'...",...,10,116,2026-01-05,branch,52,False,True,False,True,False
5077,-191.821013,219.053643,Paysandu,myriam.garcía@yahoo.com,"[{'type': 'personal', 'status': 'delinquent', ...",Other,closed,"Alameda Cassiano, 72, Frei Leopoldo, 32664-667...",UY,"[{'status': 'frozen', 'balance': 1323029.37, '...",...,10,105,2026-01-12,atm,55,true,False,False,False,False

## city

In [219]:
data['city'].str.strip().unique()

<StringArray>
[        'La Serna',         'Salvador',         'Medellin',
       'Montevideo',           'Temuco',         'Fortalza',
          'Mendoza',       'Concepcion',          'Cordoba',
         'Brasilia', 'Ciudad de Mexico',      'Guadalajara',
        'Fortaleza',            'Bogta',       'Guadalajra',
         'Cartagna',          'Brasila',            'Salto',
           'Bogota',        'Sao Paulp',            'Cusco',
          'Salvdor',       'Valparaiso',      'Barranquila',
          'Medelin',            'Saltp',          'Rosario',
            'Rivra',  'Ciudd de Mexico',     'Buenos Aires',
            'Piura',        'Maldonado',     'Barranquilla',
         'Monterry',          'Tijuana',              'Cai',
        'Cartagena',        'Sao Paulo',   'Rio de Janeiro',
         'Paysandu',         'Arequipa',        'Monterrey',
        'La Serena',             'Cali',           'Mendza',
           'Rivera',      'Buenos Aire',             'Lima',
         'Trujillo',           'Puebla',        'Montevide',
         'Santiago',          'Arequpa',          'Tucuman',
           'Rosaro',            'Temco',           'Tijana',
           'Tucman',              'Lma',             'Cusc',
    'Rio de Janero',            'Puebl',             'Piua',
         'Maldonad',        'Concepcin',          'Trujllo',
           'Cordba',          'Paysand',          'Santiag']
Length: 69, dtype: str

## email

In [220]:
EAI (Email Address Internationalization)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3252061069.py, line 1)

In [ ]:
dominios_unicos = data['email'].str.split('@').str[1].str.lower().unique()

print(f"Se encontraron {len(dominios_unicos)} dominios únicos:")
print(dominios_unicos)

Se encontraron 37 dominios únicos:
['gmail.com' 'bol.com.br' 'hotmail.com' 'yahoo.com.br' 'live.com'
 'terra.com.br' 'yahoo.com' 'icloud.com' 'uol.com.br' nan 'outlook.com.br'
 'livecom' '#hotmail.com' 'gmail.com..' 'yahoo.com..' '' 'hotmailcom'
 ' yahoo.com' '#terra.com.br' 'yahoocom' ' hotmail.com' '#gmail.com'
 '#yahoo.com.br' 'terra.com.br..' 'gmailcom' 'hotmail.com..' 'yahoocombr'
 'yahoo.com.br..' 'outlook.com.br..' '#outlook.com.br' '#yahoo.com'
 'uolcombr' 'icloudcom' ' live.com' 'uol.com.br..' ' gmail.com'
 ' icloud.com']

In [ ]:
data[data['email'].str.count('@')>1].sample(5)

,lat,lon,city,email,loans,gender,status,address,country,accounts,...,credit_info.oldest_account_age_months,digital_engagement.last_login_date,digital_engagement.preferred_channel,digital_engagement.avg_monthly_logins,digital_engagement.push_notifications,digital_engagement.paperless_statements,digital_engagement.mobile_app_registered,digital_engagement.web_banking_registered,geo_valid,geo_invalid_reason
2754,-22.234010,-70.097817,Salvador,@@isaac.ruiz@yahoo.com,"[{'type': 'education', 'status': 'default', 'l...",M,closed,"Diagonal 92 # 39-5 Sur, 709729, Ovejas, Sucre",BR,"[{'status': 'active', 'balance': 493384.97, 'c...",...,345,2025-08-16,mobile,35,True,False,False,False,True,None
3471,-29.911778,-70.670263,Temuco,@@martina.velandia@yahoo.com,"[{'type': 'auto', 'status': 'delinquent', 'loa...",M,closed,Calle San Miguel de Tucumán N° 71 Torre 7 Dto....,CL,"[{'status': 'frozen', 'balance': 322994.59, 'c...",...,322,2026-02-28,web,NaN,True,True,True,True,True,None
1734,-162.127303,316.680734,Fortaleza,@@thiago.segura@uol.com.br,"[{'type': 'personal', 'status': 'delinquent', ...",F,inactive,"Av. J.J. Castelli N° 5586 Dto. 2, Ushuaia 9410...",BR,"[{'status': 'Active', 'balance': 441038.55, 'c...",...,55,2025-06-24,branch,NaN,False,false,False,True,False,both_out_of_range
4156,-17.470683,-80.367548,Arequpa,@@facundo.rodriguez@yahoo.com,[],Other,suspended,"Estação Moreira, 454, Sport Club, 93290-018 Fe...",PE,"[{'status': 'frozen', 'balance': '441430,37', ...",...,76,2026-01-30,web,51,True,false,True,True,True,None
4169,29.592524,-104.728333,Monterrey,@@alta gracia.montoya@hotmail.com,[],F,closed,"Calle de Danilo Jaén 19 Piso 0 , Zamora, 13108",MX,"[{'status': 'frozen', 'balance': 365949.21, 'c...",...,246,2025-12-14,web,52,False,True,True,False,True,None

In [ ]:
from email_validator import validate_email, EmailNotValidError

def check_email(email):
    try:
        validate_email(email, check_deliverability=False)
        return True
    except EmailNotValidError:
        return False
data[data['email'].apply(check_email)]['email']

0              lucas.brito@gmail.com
1        oliver.montalbán@bol.com.br
2            matilda.olivé@gmail.com
3       armando.villalba@hotmail.com
4           jade.camargo@hotmail.com
                    ...
5090     mohamed.abascal@hotmail.com
5091         amador.duarte@gmail.com
5093     edelmiro.olmos@terra.com.br
5097    joaquina.martínez@bol.com.br
5098           inés.moreno@yahoo.com
Name: email, Length: 4244, dtype: str

## nationality

In [ ]:
data['nationality'].unique()

<StringArray>
['CL', 'BR', 'CO', 'UY', 'AR', 'MX', 'PE']
Length: 7, dtype: str

In [ ]:
data['phone_number'].to_csv('temp.csv')

In [ ]:
data['relationship_manager'].to_csv('temp.csv')

In [ ]:
data['credit_info.total_limit'].to_csv('temp.csv')

In [ ]:
data['digital_engagement.web_banking_registered'].unique()

array([False,  True])

In [ ]:
data['transactions'].values

array([list([{'date': '2026-04-11', 'type': 'Withdrawal', 'amount': 14039.03, 'status': 'pending', 'channel': 'pos', 'category': 'insurance', 'currency': 'USD', 'merchant': None, 'account_id': 'ACC-405300E15156', 'description': 'Acciones madrid vio trata llega debía.', 'transaction_id': 'TXN-7A7F1852B5E4'}, {'date': '05-05-2026', 'type': 'fee', 'amount': '$33593.14', 'status': 'completed', 'channel': 'mobile', 'category': 'shopping', 'currency': 'USD', 'merchant': 'Sodimac', 'account_id': 'ACC-405300E15156', 'description': 'Primeras señora habla vivir posición oficial tienen todas.', 'transaction_id': 'TXN-BBF37C53AEE4'}, {'date': '2026-03-16', 'type': 'refund', 'amount': 9307.66, 'status': 'completed', 'channel': 'pos', 'category': 'investment', 'currency': 'USD', 'merchant': 'Falabella', 'account_id': 'ACC-405300E15156', 'description': 'Ley fueron evitar poco.', 'transaction_id': 'TXN-68E6F9DE3AA7'}, {'date': '2026-04-18', 'type': 'payment', 'amount': 9451.52, 'status': 'completed', 'channel': 'mobile', 'category': 'investment', 'currency': 'USD', 'merchant': 'Spotify', 'account_id': 'ACC-405300E15156', 'description': 'Europea animales cuales construcción.', 'transaction_id': 'TXN-79802A8EC38B'}, {'date': '21/04/2026', 'type': 'refund', 'amount': 4582.02, 'status': 'failed', 'channel': 'mobile', 'category': 'shopping', 'currency': 'USD', 'merchant': 'Carrefour', 'account_id': 'ACC-405300E15156', 'description': 'Jefe capacidad toda jamás.', 'transaction_id': 'TXN-F2980A098A72'}, {'date': '2026-04-01', 'type': 'deposit', 'amount': 2791.62, 'status': 'completed', 'channel': 'atm', 'category': 'salary', 'currency': 'USD', 'merchant': 'Carrefour', 'account_id': 'ACC-920C0AE87361', 'description': 'Architecto quibusdam veniam vitae rerum.', 'transaction_id': 'TXN-B0059D4C77D7'}, {'date': '2026-03-05', 'type': 'fee', 'amount': 13053.66, 'status': 'reversed', 'channel': 'branch', 'category': 'groceries', 'currency': 'USD', 'merchant': 'IFood', 'account_id': 'ACC-920C0AE87361', 'description': '', 'transaction_id': 'TXN-6CA170370F2A'}, {'date': '2026-03-15', 'type': 'fee', 'amount': '524.68', 'status': 'pending', 'channel': 'mobile', 'category': 'utilities', 'currency': 'USD', 'merchant': 'Claro', 'account_id': 'ACC-405300E15156', 'description': 'Encima mayor alguna haya rosa mañana tu.', 'transaction_id': 'TXN-634BD8976D12'}, {'date': '28/01/2026', 'type': 'Transfer', 'amount': 14121.76, 'status': 'pending', 'channel': 'atm', 'category': 'travel', 'currency': 'USD', 'merchant': 'HomeCenter', 'account_id': 'ACC-405300E15156', 'description': 'Libro fútbol fácil función lo nuestras torno.', 'transaction_id': 'TXN-E094B09441F6'}, {'date': '20260402', 'type': 'fee', 'amount': 30591.25, 'status': 'pending', 'channel': 'web', 'category': 'transport', 'currency': 'USD', 'merchant': 'Oxxo', 'account_id': 'ACC-405300E15156', 'description': 'Francisco hospital estaba estos m habría al.', 'transaction_id': 'TXN-CABCE6F0BD37'}, {'date': '2026-03-12', 'type': 'payment', 'amount': 167132.06, 'status': 'reversed', 'channel': 'atm', 'category': 'investment', 'currency': 'PEN', 'merchant': 'HomeCenter', 'account_id': 'ACC-920C0AE87361', 'description': 'Mira principales materia él tan fuentes boca.', 'transaction_id': 'TXN-258C1981663F'}, {'date': '04-12-2026', 'type': 'fee', 'amount': 35589.07, 'status': 'reversed', 'channel': 'web', 'category': 'healthcare', 'currency': 'EUR', 'merchant': 'PedidosYa', 'account_id': 'ACC-405300E15156', 'description': 'Inventore quam sed dicta minima quis.', 'transaction_id': 'TXN-482EFCE06D2F'}, {'date': '2026-02-27', 'type': 'deposit', 'amount': 40130.57, 'status': 'completed', 'channel': 'pos', 'category': 'groceries', 'currency': 'USD', 'merchant': 'Liverpool', 'account_id': 'ACC-405300E15156', 'description': 'Est perspiciatis exercitationem nihil a exercitationem dicta.', 'transaction_id': 'TXN-7F5E60655040'}, {'date': '2026-03-08', 'type': 'payment', 'amount': 149914606.18, 'status': 'FAILED', 'channel': 'pos', 'category': 'other', 'currency': 'COP', 'merchant': 'Rappi', 'account_id': 'ACC-405300E15156', 'description': 'Pese ministro mil dejar europea boca centros.', 'transaction_id': 'TXN-616B28C396E4'}, {'date': '27/01/2026', 'type': 'fee', 'amount': 259.38, 'status': 'completed', 'channel': 'mobile', 'category': 'null', 'currency': 'USD', 'merchant': 'Liverpool', 'account_id': 'ACC-405300E15156', 'description': 'Aumento trabajo amigos sus.', 'transaction_id': 'TXN-A26DE309C481'}, {'date': '2026-04-07', 'type': 'payment', 'amount': 36309.84, 'status': 'REVERSED', 'channel': 'branch', 'category': 'entertainment', 'currency': 'USD', 'merchant': None, 'account_id': 'ACC-920C0AE87361', 'description': 'Lucha uso visita josé respuesta proyectos así.', 'transaction_id': 'TXN-2EF77B6C5429'}, {'date': '2026-04-16', 'type': 'transfer', 'amount': 9417.68, 'status': 'reversed', 'channel': 'mobile', 'category': 'insurance', 'currency': 'USD', 'merchant': 'Sodimac', 'account_id': 'ACC-405300E15156', 'description': 'Reprehenderit maxime cumque corporis eius.', 'transaction_id': 'TXN-AD0DC63FD42E'}, {'date': '2026-01-13', 'type': 'FEE', 'amount': 21924.48, 'status': 'completed', 'channel': 'pos', 'category': 'shopping', 'currency': 'USD', 'merchant': 'Linio', 'account_id': 'ACC-405300E15156', 'description': '', 'transaction_id': 'TXN-A15376F3CEC5'}, {'date': '2026-04-16', 'type': 'withdrawal', 'amount': 40331.66, 'status': 'FAILED', 'channel': 'branch', 'category': 'salary', 'currency': 'USD', 'merchant': 'Spotify', 'account_id': 'ACC-920C0AE87361', 'description': 'N/A', 'transaction_id': 'TXN-D36744480DE1'}, {'date': '2026-04-04', 'type': 'transfer', 'amount': 6457.29, 'status': 'pending', 'channel': 'pos', 'category': 'insurance', 'currency': 'USD', 'merchant': 'Spotify', 'account_id': 'ACC-405300E15156', 'description': 'Dinero tenía hablar haya silencio recursos opinión enero.', 'transaction_id': 'TXN-9D63C9E8B084'}, {'date': '20260502', 'type': 'Refund', 'amount': 32448.28, 'status': 'pending', 'channel': 'pos', 'category': 'rent', 'currency': 'USD', 'merchant': None, 'account_id': 'ACC-405300E15156', 'description': 'Quis numquam officiis distinctio praesentium quia quae.', 'transaction_id': 'TXN-534E404E6819'}, {'date': '02-27-2026', 'type': 'refund', 'amount': '183711,04', 'status': 'pending', 'channel': 'web', 'category': 'transport', 'currency': 'PEN', 'merchant': 'Uber', 'account_id': 'ACC-920C0AE87361', 'description': 'Quae voluptate alias ullam reiciendis deleniti.', 'transaction_id': 'TXN-294277AA856D'}, {'date': '2026-04-05', 'type': 'fee', 'amount': 26315.84, 'status': 'pending', 'channel': 'web', 'category': 'salary', 'currency': 'USD', 'merchant': 'Falabella', 'account_id': 'ACC-920C0AE87361', 'description': 'América muestra producto fuerzas realizar vez amigos.', 'transaction_id': 'TXN-B6864D8377D7'}, {'date': '2026-04-05', 'type': 'DEPOSIT', 'amount': 6598.91, 'status': 'completed', 'channel': 'pos', 'category': 'entertainment', 'currency': 'USD', 'merchant': 'Liverpool', 'account_id': 'ACC-920C0AE87361', 'description': '', 'transaction_id': 'TXN-BB99B85886FA'}, {'date': '2026-04-05', 'type': 'withdrawal', 'amount': 12794.95, 'status': 'pending', 'channel': 'web', 'category': 'education', 'currency': 'USD', 'merchant': 'Spotify', 'account_id': 'ACC-920C0AE87361', 'description': 'Eligendi repudiandae corrupti deserunt incidunt voluptatibus eius.', 'transaction_id': 'TXN-0873CABF57DF'}, {'date': '2026-04-17', 'type': 'payment', 'amount': 11701.85, 'status': 'FAILED', 'channel': 'web', 'category': ' subscription ', 'currency': 'USD', 'merchant': 'McDonalds', 'account_id': 'ACC-920C0AE87361', 'description': 'Quis inventore hic culpa dignissimos.', 'transaction_id': 'TXN-16CECEA20BE0'}, {'date': '2026-03-17', 'type': 'deposit', 'amount': 39254.05, 'status': 'reversed', 'channel': 'web', 'category': 'shopping', 'currency': 'USD', 'merchant': 'McDonalds', 'account_id': 'ACC-920C0AE87361', 'description': 'Blanditiis eum aperiam doloremque corrupti illo.', 'transaction_id': 'TXN-1E72ED1ABF2A'}, {'date': '01-29-2026', 'type': 'Deposit', 'amount': 47287.4, 'status': 'pending', 'channel': 'branch', 'category': 'insurance', 'currency': 'USD', 'merchant': 'Falabella', 'account_id': 'ACC-405300E15156', 'description': 'Acerca punto esos sector real plazo cuerpo.', 'transaction_id': 'TXN-C6EC6899AA73'}]),
       list([{'date': '20260127', 'type': 'payment', 'amount': 22170.95, 'status': 'pending', 'channel': 'branch', 'category': 'other', 'currency': 'USD', 'merchant': 'Tiendanube', 'account_id': 'ACC-C62719B9FC7A', 'description': 'Personas allí soy dejar principio dar.', 'transaction_id': 'TXN-84B997147B31'}, {'date': '2026-04-09', 'type': 'payment', 'amount': 39457.59, 'status': 'failed', 'channel': 'mobile', 'category': 'subscription', 'currency': 'USD', 'merchant': 'Despegar', 'account_id': 'ACC-815C1F1E4DEC', 'description': 'N/A', 'transaction_id': 'TXN-250A24EF7D16'}, {'date': '2026-03-09', 'type': 'fee', 'amount': 10947.93, 'status': 'reversed', 'channel': 'atm', 'category': 'groceries', 'currency': 'USD', 'merchant': 'Oxxo', 'account_id': 'ACC-C62719B9FC7A', 'description': 'Facilis et nesciunt amet officia nam repellendus.', 'transaction_id': 'TXN-2FBFBF772CE6'}, {'date': '2026-05-04', 'type': 'fee', 'amount': 15305.75, 'status': 'failed', 'channel': 'pos', 'category': 'subscription', 'currency': 'USD', 'merchant': 'IFood', 'account_id': 'ACC-815C1F1E4DEC', 'description': 'Sabía manera tan victoria debido alrededor existe.', 'transaction_id': 'TXN-702B67518F5D'}, {'date': '2026-02-01', 'type': 'withdrawal', 'amount': 29353.97, 'status': 'reversed', 'channel': 'mobile', 'category': 'insurance', 'currency': 'USD', 'merchant': 'Liverpool', 'account_id': 'ACC-C62719B9FC7A', 'description': 'Iusto reiciendis in consectetur odit asperiores provident.', 'transaction_id': 'TXN-40EF5C0C91C4'}, {'date': '2026-04-11', 'type': 'refund', 'amount': 25994.05, 'status': 'REVERSED', 'channel': 'web', 'category': 'dining', 'currency': 'USD', 'merchant': 'Rappi', 'account_id': 'ACC-815C1F1E4DEC', 'description': 'null', 'transaction_id': 'TXN-A303C62EA40C'}]),
       list([{'date': '2025-07-03', 'type': 'refund', 'amount': 30667462.64, 'status': 'pending', 'channel': 'mobile', 'category': 'shopping', 'currency': 'COP', 'merchant': 'Liverpool', 'account_id': 'ACC-315F40349973', 'description': 'Baja su libre necesario.', 'transaction_id': 'TXN-EB355002BD55'}, {'date': '2026-05-01', 'type': 'payment', 'amount': 80477651.02, 'status': 'completed', 'channel': 'pos', 'category': 'healthcare', 'currency': 'COP', 'merchant': 'Coppel', 'account_id': 'ACC-CEEC696B68AB', 'description': 'Podría entrar calle nacional dio.', 'transaction_id': 'TXN-F8D9424CEB94'}, {'date': '2025-07-07', 'type': 'fee', 'amount': 25974.04, 'status': 'reversed', 'channel': 'atm', 'category': '  investment  ', 'currency': 'USD', 'merchant': 'Netflix', 'account_id': 'ACC-073C58187F7C', 'description': 'Recursos ante durante plaza.', 'transaction_id': 'TXN-A54CDFDC2957'}, {'date': '20260415', 'type': 'deposit', 'amount': 103506858.53, 'status': 'completed', 'channel': 'web', 'category': 'shopping', 'currency': 'COP', 'merchant': 'MercadoLibre', 'account_id': 'ACC-5CB5277C8118', 'description': 'NA', 'transaction_id': 'TXN-A335D3D3740D'}, {'date': '25/03/2026', 'type': 'transfer', 'amount': 62251935.66, 'status': 'reversed', 'channel': 'web', 'category': 'travel', 'currency': 'COP', 'merchant': 'HomeCenter', 'account_id': 'ACC-315F40349973', 'description': 'Quibusdam dignissimos reprehenderit dicta.', 'transaction_id': 'TXN-AD24493F4F55'}, {'date': '2025-10-22', 'type': 'fee', 'amount': 127250954.58, 'status': 'failed', 'channel': 'mobile', 'category': 'entertainment', 'currency': 'COP', 'merchant': 'Carrefour', 'account_id': 'ACC-5CB5277C8118', 'description': 'Rerum deserunt corporis accusantium.', 'transaction_id': 'TXN-0BAF5A7E24DB'}, {'date': '20251013', 'type': 'refund', 'amount': '10478.16', 'status': 'pending', 'channel': 'mobile', 'category': 'rent', 'currency': 'USD', 'merchant': 'Coppel', 'account_id': 'ACC-073C58187F7C', 'description': 'Solamente varios países dado primera ideas.', 'transaction_id': 'TXN-3FB13496ADC3'}, {'date': '2026-05-04', 'type': 'refund', 'amount': 170557031.85, 'status': 'reversed', 'channel': 'web', 'category': 'transport', 'currency': 'COP', 'merchant': 'Coppel', 'account_id': 'ACC-CEEC696B68AB', 'description': 'Mayor va llegado pocos sin.', 'transaction_id': 'TXN-78945802D9C9'}, {'date': '20260319', 'type': 'fee', 'amount': 31118.36, 'status': 'completed', 'channel': 'pos', 'category': 'travel', 'currency': 'USD', 'merchant': 'Walmart', 'account_id': 'ACC-073C58187F7C', 'description': 'Dolore minus natus saepe dolorum esse harum voluptate.', 'transaction_id': 'TXN-4BB5F3F7CF38'}, {'date': '12/12/2025', 'type': 'deposit', 'amount': 25822.29, 'status': 'pending', 'channel': 'web', 'category': 'subscription', 'currency': 'EUR', 'merchant': 'Netflix', 'account_id': 'ACC-5CB5277C8118', 'description': 'Visto marco económica van.', 'transaction_id': 'TXN-4A2E75F1370E'}, {'date': '2025-06-22', 'type': 'withdrawal', 'amount': 5812.51, 'status': 'reversed', 'channel': 'branch', 'category': 'utilities', 'currency': 'USD', 'merchant': 'Linio', 'account_id': 'ACC-073C58187F7C', 'description': 'Mañana operación si memoria.', 'transaction_id': 'TXN-7296E9297E8D'}, {'date': '2025-10-22', 'type': 'payment', 'amount': 172131063.51, 'status': 'pending', 'channel': 'branch', 'category': 'other', 'currency': 'COP', 'merchant': 'PedidosYa', 'account_id': 'ACC-315F40349973', 'description': 'Expedita similique magnam tenetur enim nulla consequuntur repudiandae.', 'transaction_id': 'TXN-60DA28249647'}, {'date': '2026-04-20', 'type': 'pago', 'amount': 36676459.07, 'status': 'pending', 'channel': 'pos', 'category': 'travel', 'currency': 'COP', 'merchant': 'Falabella', 'account_id': 'ACC-CEEC696B68AB', 'description': 'Lenguaje cabeza santiago amigo medidas defensa tiempos.', 'transaction_id': 'TXN-3CD6BC96C05E'}, {'date': '2025-05-24', 'type': 'withdrawal', 'amount': 79.06, 'status': 'pending', 'channel': 'web', 'category': 'dining', 'currency': 'USD', 'merchant': 'HomeCenter', 'account_id': 'ACC-073C58187F7C', 'description': 'Objeto poco texto todavía.', 'transaction_id': 'TXN-31B7F8687FC7'}, {'date': '10-09-2025', 'type': 'Pago', 'amount': 40699.72, 'status': 'reversed', 'channel': 'atm', 'category': 'transport', 'currency': 'USD', 'merchant': 'Carrefour', 'account_id': 'ACC-073C58187F7C', 'description': 'Acuerdo primer relaciones mejores tiempo seguir.', 'transaction_id': 'TXN-15C1FEDBAF02'}, {'date': '2026-04-24', 'type': 'deposit', 'amount': 189926195.27, 'status': 'failed', 'channel': 'web', 'category': None, 'currency': 'COP', 'merchant': 'Walmart', 'account_id': 'ACC-CEEC696B68AB', 'description': 'Ii habían contenido jamás fernando asunto aparece piel.', 'transaction_id': 'TXN-558F63EACCDE'}, {'date': '2026-02-26', 'type': 'fee', 'amount': 40941.25, 'status': 'FAILED', 'channel': 'pos', 'category': 'subscription', 'currency': 'USD', 'merchant': 'Uber', 'account_id': 'ACC-073C58187F7C', 'description': 'García respecto ex buenos vamos.', 'transaction_id': 'TXN-69E3DC1F91A3'}, {'date': '2025-12-31', 'type': 'deposit', 'amount': 340475.21, 'status': 'failed', 'channel': 'pos', 'category': 'utilities', 'currency': 'MXN', 'merchant': 'Liverpool', 'account_id': 'ACC-073C58187F7C', 'description': None, 'transaction_id': 'TXN-C5F651111C89'}, {'date': '2026-05-04', 'type': 'withdrawal', 'amount': 36623555.25, 'status': 'pending', 'channel': 'branch', 'category': 'transport', 'currency': 'COP', 'merchant': 'Netflix', 'account_id': 'ACC-CEEC696B68AB', 'description': 'San capital agua televisión.', 'transaction_id': 'TXN-9EB9D3021161'}]),
       ...,
       list([{'date': '2026-04-28', 'type': 'FEE', 'amount': 30698.75, 'status': 'pending', 'channel': 'mobile', 'category': 'groceries', 'currency': 'USD', 'merchant': 'Netflix', 'account_id': 'ACC-2232324C2365', 'description': 'Barcelona interior dejar visita conseguir b.', 'transaction_id': 'TXN-C75B00450C3C'}, {'date': '2024-05-02', 'type': 'fee', 'amount': 11061.85, 'status': 'REVERSED', 'channel': 'atm', 'category': 'shopping', 'currency': 'USD', 'merchant': 'McDonalds', 'account_id': 'ACC-A6B4D4820A6E', 'description': 'Voluptatum neque ipsum aliquam placeat sequi.', 'transaction_id': 'TXN-12B89D76D7FF'}, {'date': '2025-02-09', 'type': 'PAYMENT', 'amount': 33980.25, 'status': 'completed', 'channel': 'web', 'category': 'travel', 'currency': 'USD', 'merchant': 'Despegar', 'account_id': 'ACC-A6B4D4820A6E', 'description': 'Dignissimos est odio quos blanditiis adipisci similique.', 'transaction_id': 'TXN-8DC93A78832C'}, {'date': '2025-10-11', 'type': 'withdrawal', 'amount': 30869.91, 'status': 'completed', 'channel': 'mobile', 'category': 'salary', 'currency': 'USD', 'merchant': 'Didi', 'account_id': 'ACC-2232324C2365', 'description': 'Alguna ese rodríguez quería.', 'transaction_id': 'TXN-7CB7DBE78A1C'}, {'date': '2025-09-26', 'type': 'withdrawal', 'amount': 693.47, 'status': 'FAILED', 'channel': 'branch', 'category': 'salary', 'currency': 'USD', 'merchant': 'Claro', 'account_id': 'ACC-A6B4D4820A6E', 'description': 'null', 'transaction_id': 'TXN-DBE72AD76E7D'}, {'date': '2024-09-13', 'type': 'refund', 'amount': 29266.1, 'status': 'failed', 'channel': 'mobile', 'category': 'utilities', 'currency': 'PEN', 'merchant': 'Amazon', 'account_id': 'ACC-A6B4D4820A6E', 'description': 'Fugiat iure ea omnis suscipit.', 'transaction_id': 'TXN-86970ABE3B01'}, {'date': '2024-09-30', 'type': 'fee', 'amount': '31728,99', 'status': 'completed', 'channel': 'pos', 'category': 'entertainment', 'currency': 'USD', 'merchant': 'Carrefour', 'account_id': 'ACC-D01FF1D34469', 'description': 'D dios cabo hombre.', 'transaction_id': 'TXN-0CB77574D41A'}, {'date': '2026-03-12', 'type': 'withdrawal', 'amount': 27727.56, 'status': 'reversed', 'channel': 'web', 'category': 'subscription', 'currency': 'USD', 'merchant': 'Despegar', 'account_id': 'ACC-8B9CCBF81E47', 'description': 'Iglesia educación artículo m peso.', 'transaction_id': 'TXN-E026488A3148'}, {'date': '2025-04-10', 'type': 'REFUND', 'amount': 33268.23, 'status': 'completed', 'channel': 'atm', 'category': 'insurance', 'currency': 'USD', 'merchant': 'Movistar', 'account_id': 'ACC-A6B4D4820A6E', 'description': 'NA', 'transaction_id': 'TXN-43DA1A47A00A'}, {'date': '2025-12-16', 'type': 'refund', 'amount': 9636.49, 'status': 'COMPLETED', 'channel': 'mobile', 'category': 'insurance', 'currency': 'USD', 'merchant': 'McDonalds', 'account_id': 'ACC-2232324C2365', 'description': 'Principio pueda este mismos.', 'transaction_id': 'TXN-D23F3566BCE7'}, {'date': '2025-12-29', 'type': 'Deposito', 'amount': 13075.46, 'status': 'reversed', 'channel': 'mobile', 'category': 'salary', 'currency': 'USD', 'merchant': 'Falabella', 'account_id': 'ACC-8B9CCBF81E47', 'description': 'Frente partido número mismo mes.', 'transaction_id': 'TXN-8909FF300C3E'}, {'date': '03-13-2026', 'type': 'transfer', 'amount': 18269979.7, 'status': 'failed', 'channel': 'mobile', 'category': 'utilities', 'currency': 'CLP', 'merchant': 'Falabella', 'account_id': 'ACC-2232324C2365', 'description': 'Eligendi cupiditate illo quo ipsam.', 'transaction_id': 'TXN-5BB18D71BA1D'}, {'date': '20260416', 'type': 'withdrawal', 'amount': 7246.13, 'status': 'FAILED', 'channel': 'atm', 'category': 'education', 'currency': 'USD', 'merchant': 'Starbucks', 'account_id': 'ACC-8B9CCBF81E47', 'description': 'Instituto dicho ella materia rafael sigue mi población.', 'transaction_id': 'TXN-60B4A4ABD73B'}, {'date': '2026-03-10', 'type': 'withdrawal', 'amount': 35850.86, 'status': 'failed', 'channel': 'mobile', 'category': 'healthcare', 'currency': 'USD', 'merchant': 'Falabella', 'account_id': 'ACC-8B9CCBF81E47', 'description': 'Eius laudantium consequatur necessitatibus nihil doloribus.', 'transaction_id': 'TXN-CF4672BDB94D'}]),

In [141]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')

# Write query to get date, tmax, and tmin from weather
query = """
SELECT *
  FROM silver.digital_engagement;
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

# credit_info

In [317]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')
tables = ['silver.credit_info','silver.digital_engagement','silver.stg_customers']
# Write query to get date, tmax, and tmin from weather
query = f"""
select *
from {tables[0]}
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [247]:
df.columns

Index(['customer_id', 'credit_score', 'utilization_pct', 'total_limit',
       'total_used', 'oldest_account_age_months', 'late_payments_12m',
       'inquiries_6m', 'bankruptcy_flag'],
      dtype='str')

In [262]:
df['credit_score'].isna().sum()

np.int64(19)

## utilization_pct

In [285]:
df['credit_score'].isna().sum()

np.int64(902)

puesto que no podemos saber si fue un error al ingresar USD de más o utilizar

In [102]:
df

,last_login_date,preferred_channel,avg_monthly_logins,push_notifications,paperless_statements,mobile_app_registered,web_banking_registered
0,2025-12-23,phone,60,False,True,True,False
1,2025-08-16,branch,20,False,True,False,True
2,20251102,phone,39,True,True,True,False
3,2025-06-24,branch,6,True,False,False,False
4,17/03/2026,mobile,57,True,True,True,False
...,...,...,...,...,...,...,...
5095,2026-03-17,atm,19,False,False,True,True
5096,2025-09-09,mobile,5,True,True,False,False
5097,2026-04-30,mobile,9,False,False,True,False
5098,2025-09-21,phone,50,False,False,False,True
5099,04/08/2025,web,6,False,True,False,False

## total_limit

In [292]:
df['total_limit'].isna().sum()

np.int64(0)

In [307]:
import pandas as pd

def convertible_a_entero(serie: pd.Series) -> pd.Series:
    """
    Recibe una serie de pandas y retorna una serie con los valores únicos
    que NO se pueden convertir a números flotantes.
    """
    # 1. Intentamos la conversión. Los errores se convierten en NaN
    conversion = pd.to_numeric(serie, errors='coerce')
    
    # 2. Filtramos la serie original donde la conversión falló (es NaN)
    # y usamos .unique() para no repetir los mismos errores
    valores_invalidos = serie[conversion.isna()].unique()
    
    return valores_invalidos

In [293]:
list(obtener_no_convertibles(df['total_limit']))

[]

## total_used

In [297]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')
tables = ['silver.credit_info','silver.digital_engagement','silver.stg_customers']
# Write query to get date, tmax, and tmin from weather
query = f"""
select *
from {tables[0]}
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [301]:
df['total_used'].values[0]

np.float64(744892.18)

In [299]:
list(obtener_no_convertibles(df['total_used']))

[]

## oldest_account_age_months

In [313]:
import pandas as pd

def no_convertible_a_entero(serie: pd.Series) -> pd.Series:
    """
    Recibe una serie de pandas y retorna una serie con los valores únicos
    que NO se pueden convertir a números flotantes.
    """
    # 1. Intentamos la conversión. Los errores se convierten en NaN
    conversion = pd.to_numeric(serie, errors='coerce')
    
    # 2. Filtramos la serie original donde la conversión falló (es NaN)
    # y usamos .unique() para no repetir los mismos errores
    valores_invalidos = serie[conversion.isna()].unique()
    
    return valores_invalidos

In [308]:
no_convertible_a_entero(df['oldest_account_age_months'])

<ArrowStringArray>
[]
Length: 0, dtype: str

## late_payments_12m

In [310]:
no_convertible_a_entero(df['late_payments_12m'])

<ArrowStringArray>
[]
Length: 0, dtype: str

## inquiries_6m

In [312]:
no_convertible_a_entero(df['inquiries_6m'])

<ArrowStringArray>
[]
Length: 0, dtype: str

## bankruptcy_flag

In [319]:
df['bankruptcy_flag']

0        True
1       False
2        True
3        True
4        True
        ...
4995     True
4996     True
4997     True
4998    False
4999    False
Name: bankruptcy_flag, Length: 5000, dtype: bool

# digital_engagement

In [580]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')
tables = ['silver.credit_info','silver.digital_engagement','silver.stg_customers']
# Write query to get date, tmax, and tmin from weather
query = f"""
select *
from silver.customers
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [534]:
df['country'].unique()

<ArrowStringArray>
['BR', 'AR', 'MX', 'PE', 'UY', 'CO', 'CL']
Length: 7, dtype: str

In [583]:
df['risk_score'].isna().sum()

np.int64(0)

In [582]:
df['risk_score'].unique()

array([87.24, 19.62, 22.45, ..., 66.99, 13.9 , 28.66], shape=(3937,))

In [561]:
df['lat'].isna().sum()

np.int64(237)

In [463]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7663 entries, 0 to 7662
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          7663 non-null   str
 1   loan_id              7663 non-null   str
 2   type                 7663 non-null   str
 3   principal            7663 non-null   float64
 4   outstanding_balance  7663 non-null   float64
 5   interest_rate        7663 non-null   float64
 6   term_months          7663 non-null   float64
 7   monthly_payment      7663 non-null   float64
 8   start_date           7663 non-null   object
 9   end_date             7663 non-null   object
 10  status               7663 non-null   str
 11  days_past_due        7663 non-null   float64
 12  collateral_type      6842 non-null   str
dtypes: float64(6), object(2), str(5)
memory usage: 1.1+ MB

In [429]:
import pandas as pd

def no_convertible_a_entero(serie: pd.Series) -> pd.Series:
    """
    Recibe una serie de pandas y retorna una serie con los valores únicos
    que NO se pueden convertir a números flotantes.
    """
    # 1. Intentamos la conversión. Los errores se convierten en NaN
    conversion = pd.to_numeric(serie, errors='coerce')
    
    # 2. Filtramos la serie original donde la conversión falló (es NaN)
    # y usamos .unique() para no repetir los mismos errores
    valores_invalidos = serie[conversion.isna()].unique()
    
    return valores_invalidos
no_convertible_a_entero(df['interest_rate'])

<ArrowStringArray>
[]
Length: 0, dtype: str

In [488]:
df['credit_limit']

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...
17524         NaN
17525         NaN
17526    38031.18
17527         NaN
17528         NaN
Name: credit_limit, Length: 17529, dtype: float64

In [439]:
df['term_months'].unique()

<ArrowStringArray>
['24', '180', '120', '36', '360', '60', '12', '84', '48', '240']
Length: 10, dtype: str

In [434]:
list(df['interest_rate'].unique())

np.float64(3.01)

In [419]:
df

Index(['load_timestamp', 'customer_id', 'loan_id', 'type', 'principal',
       'outstanding_balance', 'interest_rate', 'term_months',
       'monthly_payment', 'start_date', 'end_date', 'status', 'days_past_due',
       'collateral_type'],
      dtype='str')

In [414]:
df['description'].isna().sum()

np.int64(8946)

In [411]:
list(df['description'].unique())

['Fueron paz grande.',
 'Placeat vel impedit fuga.',
 'Líder horas tipos siete victoria ella calidad.',
 'Cuando cómo nueva dijo asimismo tal peor reforma.',
 'Cuerpo fuerte que conocer.',
 'Serán nuevas soy nuevo producto sur.',
 'Sola común aire presidente saber mí a cada.',
 'Otras expresión tampoco alto armas rodríguez cuando.',
 'Septiembre saber hay cuyo interior.',
 'Importancia mismos éste madrid lucha nuestros.',
 'Veritatis quae veritatis inventore.',
 'Larga tierra fecha secretario casos durante.',
 'Otros buen sector cargo esto arte cuanto región.',
 'Corrupti eligendi veritatis inventore eaque.',
 'Lejos importancia durante pasa.',
 'Hospital mayo rafael barcelona cosas posición aquellos.',
 'Instituciones punto blanco.',
 'Ea facere alias aliquam blanditiis tempora magnam.',
 'Relaciones partidos universidad blanca igual campo había.',
 'Movimiento buscar miembros.',
 'Laborum necessitatibus cum dolores iusto sapiente.',
 'Perspiciatis veritatis unde repudiandae expedita.',
 'Negro tiempos amigo humano llevar.',
 'NA',
 'Mujeres toma casa vuelve mejores investigación era.',
 'Algún curso puso aquellas.',
 '',
 'Ut soluta autem culpa quis eum a.',
 'Medios o teoría alto donde podrá especial.',
 'Vitae nesciunt a at ea commodi.',
 'Voluptatibus repellendus magnam inventore.',
 'Próximo ciudad película prensa.',
 'Deleniti cumque fugit ipsam.',
 'Noviembre chile arte unión carta corte pedro.',
 'Comenzó mil campaña riesgo existencia.',
 'Puedo bueno buenos uso paso.',
 'Veces han estuvo madrid vuelve.',
 'Ipsa magnam sint vero.',
 'Non pariatur nam atque similique excepturi.',
 'N/A',
 'Distintos intereses cuadro desarrollo todos.',
 'Tienen ha área quizá menor.',
 'Dolorum quae facere minima alias reprehenderit.',
 'Han trabajo precisamente derechos general.',
 'Maxime recusandae culpa fugit.',
 'Ninguna días cantidad última flores ésta televisión.',
 'Hijos zona tema supuesto misma.',
 'Ocasión español premio país abril un.',
 'Iure deleniti aliquam veritatis tempore.',
 'Voluptas tenetur id delectus delectus.',
 'Llegado efecto marco tenían.',
 'Tierra violencia pensar esta entonces c.',
 'Quos distinctio officia aliquid rerum numquam et doloribus.',
 'Población o mal chile cualquier o luis.',
 'Crecimiento económico operación diversas.',
 nan,
 'Color principales lado algunas sector serán veces partir.',
 'null',
 'Sueño alto mejor segunda.',
 'Piel máximo programas primer ambiente teatro supuesto c.',
 'Cama proyecto tratamiento psoe.',
 'Ésta oposición cosa juicio martín ejemplo.',
 'Premio partir poner nuestra.',
 'Nostrum occaecati commodi aperiam labore eos.',
 'Cosa años debía serán s.',
 'Natus molestias ad fugiat quas suscipit praesentium.',
 'Aperiam temporibus libero impedit dolorem culpa iste.',
 'Fugiat molestiae reiciendis ipsum optio.',
 'Ser semanas asunto capital lado aspectos.',
 'Jóvenes hacen pasa.',
 'Están segunda señaló debido medidas ni ya.',
 'Ipsum in possimus tempora eaque suscipit nesciunt.',
 'Aliquid incidunt iste dolor.',
 'Instituto asunto precisamente mar vio meses nada.',
 'Silencio tema club allí arte u.',
 'Nuevo vida humanos primer corte.',
 'Consectetur minima vitae voluptatem ut.',
 'Laborum dolorem atque eaque mollitia expedita voluptatibus.',
 'Pasar voluntad efecto ésta igual podría.',
 'Texto idea decía salir posibilidades pese.',
 'Situación recuerdo paz diversas gran.',
 'Siempre amor ideas mercado me trabajadores solución.',
 'Ex nostrum impedit est quam.',
 'Possimus voluptate nulla quas iusto ad.',
 'Siendo cinco pedro estaba mujer importancia vino.',
 'Nihil eius consectetur veniam velit ullam sapiente.',
 'Siguiente materia alto buscar defensa.',
 'Especialmente destino de económico quienes abril.',
 'Tribunal alguna ese medio.',
 'Commodi repudiandae aut porro quidem dolore.',
 'Hacer democracia contrario ir.',
 'Asimismo director calidad ser decisión libertad.',
 'Molestiae voluptatibus veniam expedita nulla ab cum.',
 'Estado cuadro haciendo.',
 'Pronto toda popular actual aún prensa campo.',
 'Dos llega diez.',
 'Artículo somos partes figura i.',
 'Estoy tuvo parece hermano.',
 'Cuya cultura fuerte cierta aspectos peor ir.',
 'El pronto tampoco ésta pesar.',
 'El aunque desde bueno sobre ministerio hacía.',
 'Unos países don octubre enfermedad.',
 'Luego cine sus doctor tengo meses.',
 'Ipsum rem deleniti modi accusamus neque.',
 'Rodríguez si desde nuevas i fuerza mes principio.',
 'Menos ley esta blanca informe mucha.',
 'Vel eaque saepe corrupti quam pariatur odio.',
 'Nihil laboriosam quibusdam aliquid.',
 'Sapiente sit dolores quis.',
 'Distinctio dolores quidem iusto aliquam corrupti.',
 'Deleniti officiis explicabo maiores inventore occaecati dolorem.',
 'Vero impedit natus nulla nihil consectetur veniam.',
 'Oro voy menos cuba m policía niño.',
 'Políticos j poner serán solución.',
 'Aspernatur sunt natus facere necessitatibus fugit.',
 'Omnis deleniti modi veniam.',
 'Humano problemas construcción ha.',
 'Facilis cumque porro totam eius qui.',
 'Dicta cupiditate itaque similique est deserunt ducimus.',
 'Primer cuales todas.',
 'Opinión etapa allí otras josé.',
 'Commodi facilis ut officiis saepe tempora veritatis natus.',
 'Quidem perspiciatis nam distinctio possimus.',
 'Zona su resulta seis crisis ideas vuelve etapa.',
 'Estaban mar sol hablar fin serie.',
 'Eos porro temporibus laudantium vel voluptates dolore cupiditate.',
 'Tengo hombres dejar número permite.',
 'Particular alrededor pesar ocasión.',
 'Fuerzas menor joven cargo.',
 'Dolorum nesciunt incidunt aliquid amet natus unde culpa.',
 'Nuestros puede oposición programas económica.',
 'Sigue banco juan creación.',
 'Rerum dignissimos veritatis iure distinctio suscipit.',
 'In amet tempora commodi nihil voluptatem occaecati recusandae.',
 'Voluptatibus quod fuga fugit hic molestias.',
 'Quae aspernatur excepturi ex.',
 'Nemo maxime tempore repellendus aut.',
 'Segunda con negro negro niveles etapa esto.',
 'Nisi ipsum sunt optio ratione.',
 'Nuevas unos muy sur.',
 'Sentido tenían n gran.',
 'Sapiente nobis illum temporibus quod iusto.',
 'Minima placeat repudiandae omnis.',
 'Estoy seguridad flores.',
 'Hijo muestra naturaleza aquí energía media.',
 'Sapiente architecto vero.',
 'Arte tratamiento felipe salir maría viaje blanca.',
 'Reiciendis labore occaecati hic saepe eos quas non.',
 'Similique pariatur inventore aperiam quisquam nesciunt nemo.',
 'Quae quisquam voluptates fugit labore.',
 'Capaz figura unidos relaciones.',
 'Sólo ambiente tenían alta españa.',
 'Magni quasi nobis distinctio.',
 'Tempora odit doloribus dignissimos asperiores cupiditate.',
 'Es española sentido cuya peor ambos quiero.',
 'Con zona iba chile juez.',
 'Illum dignissimos possimus reprehenderit eius exercitationem corrupti.',
 'Nesciunt necessitatibus possimus quaerat repellat dolore repudiandae.',
 'Todas últimos paz cómo obstante cantidad principales.',
 'Suscipit doloribus ad laborum dolores.',
 'Unde nesciunt quibusdam ducimus.',
 'Odit assumenda porro mollitia.',
 'Toma ir minutos participación.',
 'Casi países humana vuelve.',
 'Earum perspiciatis facere explicabo laboriosam magnam aliquam quaerat.',
 'Días diversos aquel habían.',
 'Nulla maxime dicta corporis harum.',
 'C negro permite lado estos tipos ella.',
 'Dicta voluptatibus eos sint molestiae.',
 'Quia laborum eius deserunt exercitationem voluptas.',
 'Similique minima aut iste nam beatae inventore labore.',
 'Mujeres nunca estos he cualquier mitad mesa.',
 'Numquam cupiditate beatae soluta itaque maiores.',
 'Agua cabo congreso local.',
 'Diciembre social volver familia luis.',
 'Espacio hablar pensar pasar cómo hace.',
 'Posibilidades salida estuvo nuestros democracia va visto.',
 'Natus accusamus consectetur eligendi reprehenderit eum.',
 'Suficiente ocasiones crisis texto.',
 'Eum dolor voluptate neque non.',
 'Adipisci aut recusandae tempore distinctio.',
 'Radio régimen puntos tipo comercio estudio.',
 'Necesario j fuerza habla lo dirección principal.',
 'Pesetas temas cuestión pasó deja producción.',
 'Sin libertad dicen función uno san.',
 'Siguientes unos policía podía largo última.',
 'Non quaerat facere architecto.',
 'Más casos momentos calidad luego largo.',
 'Manuel encuentro teoría dios pie considera común.',
 'Doloremque ratione at.',
 'Vio casos tampoco salud algún señaló.',
 'Odio doloremque ullam qui veritatis sed.',
 'Dice da partes obstante trata eran.',
 'Libertad rey encontrar otros.',
 'Española recuerdo distintas consejo dinero grado cambio pero.',
 'Voluntad años quien.',
 'Inventore reprehenderit dolores cumque nemo atque exercitationem.',
 'Secretario diciembre partidos entrar partir silencio había.',
 'Madrid grado alto atrás.',
 'Dólares tanto trabajo ni acto primero pública.',
 'Provident quo in voluptatum.',
 'Nobis placeat eveniet tempore amet.',
 'Dólares millones media está plan y.',
 'Ir cosa año control adelante comercio.',
 'Manera sola soy les frente cultural prueba reforma.',
 'Etc medio única dar.',
 'Jorge características cara relaciones cierto fiscal.',
 'Parece estilo p ministro modo informe.',
 'Mercado española tipos llega.',
 'Vino problemas efecto control calle.',
 'Pone vuelta tras generales libro en políticos.',
 'Económica como música era función solución.',
 'Justicia dos puesto mayor secretario mejor sus.',
 'Animi eius odit optio quos optio.',
 'Lado aun nuestro hasta casi.',
 'Comercio aquella hospital industria.',
 'Sea resultados miguel misma nacional.',
 'Puso encuentro medios m doctor tipo juicio.',
 'Unde aspernatur eius incidunt accusamus explicabo laborum debitis.',
 'Explicabo cupiditate alias porro quod optio.',
 'Unde cupiditate voluptatum.',
 'Forma único primero ayuda.',
 'Dolore facere necessitatibus magni.',
 'Edad llama saber hay efecto.',
 'Mi país dios familia premio.',
 'Sequi repudiandae quisquam culpa corrupti cum sed.',
 'Nobis a provident facere officiis animi qui.',
 'Color población en muerte fuerzas.',
 'Cuadro pablo especial nada francisco esto pensar.',
 'Eum harum ipsam.',
 'Llama fiscal sector está i.',
 'Actividad opinión tiempos tuvo.',
 'Reprehenderit rem eaque non iusto dicta quam.',
 'Realidad cabo santiago superior apoyo siendo.',
 'Ab voluptas quaerat magnam assumenda.',
 'Serie radio jorge pasa total.',
 'Sint qui fugit illo quibusdam dicta possimus.',
 'Quisquam fugit quae impedit saepe.',
 'Nam unde libero at corporis aliquam magnam.',
 'Beatae eum tenetur amet veritatis ad doloremque.',
 'Nobis officiis minima et.',
 'Conocer suficiente momento términos.',
 'Estructura abril población felipe instituto necesario amigo.',
 'Voluptate iusto dignissimos numquam optio in eaque omnis.',
 'Animi reiciendis laudantium perspiciatis at ducimus consequatur.',
 'Sunt debitis laudantium neque fugiat nihil.',
 'Magnam illo amet blanditiis corrupti tenetur modi.',
 'Los manuel corazón silencio serie negro especialmente.',
 'Deserunt facere laboriosam alias ducimus minus.',
 'No hizo tenido momento.',
 'Veniam corrupti quos dolores hic fugit sunt.',
 'Amigos guerra productos último televisión.',
 'Medidas últimos encuentro propio sean gran.',
 'Mundial distintas razón líder.',
 'Quasi dolorem inventore doloribus sit dolor.',
 'Mantener efecto tendrá esta derecho centros política.',
 'Maxime harum tempora facere accusamus voluptates.',
 'Joven mil falta c internacional papel formación.',
 'Consectetur deserunt nobis pariatur esse vero.',
 'Obra nuevo principal términos menor visita ii.',
 'Esse voluptatibus tenetur repudiandae non similique optio.',
 'U a encuentra niveles.',
 'Quam porro quae tempore maiores iure officia.',
 'Vista camino noche movimiento fernando sur mediante hacia.',
 'Domingo busca joven dinero control autoridades.',
 'Totam vitae repellat mollitia temporibus est.',
 'Saber población cada instituciones caso decisión industria.',
 'Aut sed autem molestiae accusamus aspernatur deleniti modi.',
 'Porro natus libero ducimus deserunt.',
 'Illum atque iusto corporis magni cumque quos.',
 'Autem a ipsa nisi magnam culpa saepe.',
 'Commodi incidunt ipsam doloremque quam neque.',
 'Cabo este cabeza nada obras mayoría.',
 'Entrar dos universidad entrar difícil madrid tiempos martín.',
 'Civil boca datos.',
 'Carne trata final especial tomar aún vuelta.',
 'At veritatis ratione occaecati officiis.',
 'Derecho cambios empresas claro realidad condiciones hacia.',
 'Partes hoy casos francisco mismo casa martín.',
 'Están salir centros congreso buscar.',
 'Natus dicta maiores distinctio.',
 'Quaerat voluptates libero ex delectus distinctio voluptatibus magni.',
 'Sabía partir primer deja igual llegar.',
 'Distinctio earum adipisci voluptas minima quae nesciunt.',
 'Nobis ad eaque et nulla.',
 'Mi hermano debido pocos investigación pedro últimos programas.',
 'Provident facilis dolores saepe.',
 'Problemas energía me condiciones alguien común.',
 'Blanditiis nulla enim mollitia.',
 'Alias delectus nisi.',
 'Necessitatibus sed necessitatibus dolorum assumenda.',
 'Director mañana ayuda pequeño realidad diferencia.',
 'Quaerat aperiam amet nulla corporis magni.',
 'Vino desarrollo número se aspecto acciones.',
 'Dicen solo pesar.',
 'Viejo frente cuya.',
 'Precio hombres otro rosa plan lenguaje manuel.',
 'Praesentium laboriosam sint architecto nesciunt voluptatem hic deserunt.',
 'Pp hablar defensa reunión total resultados aun.',
 'Eos distinctio suscipit officiis in rem minus.',
 'Adipisci quibusdam neque.',
 'Tenemos menos iglesia entrar vida pequeña sueño.',
 'Laborum voluptates sunt vitae.',
 'Violencia hacia están cantidad.',
 'Suficiente área tan demás sería.',
 'Fecha porque mi he queda español club.',
 'Carrera tienen afirmó.',
 'Muy políticas joven adelante si misma juan.',
 'Est facere soluta facilis.',
 'Estaban sobre decir doctor.',
 'Sigue sido tiempo mil.',
 'Dolor fugit quibusdam corrupti modi placeat.',
 'Voluptate porro odio.',
 'Exercitationem repudiandae libero expedita provident facere.',
 'Quod necessitatibus tenetur omnis occaecati distinctio enim.',
 'Algo recuerdo padre podemos objeto capital.',
 'Eran mirada mayor ante sus poder tan.',
 'Recusandae occaecati sequi eos quia reprehenderit maiores.',
 'Sentido prueba datos puedo corte.',
 'Enero libro cómo costa conocimiento diario.',
 'Crisis llamado abril menos ii.',
 'Nihil cum et dolor magni quis animi.',
 'Hacía objeto mí frente queda campo fueron.',
 'Vivir cabo favor cada.',
 'Ir período pasar medidas juez n.',
 'Odit soluta corporis iure.',
 'Profesional muestra luego pasado resulta señor incluso.',
 'Aquella premio punto alta además.',
 'Ipsum libero perferendis consequatur.',
 'Apoyo d hospital curso vuelve este alguien cine.',
 'Martín domingo real nueva ser alguna plan.',
 'Investigación concepto juego.',
 'Juicio ahí partidos.',
 'Condiciones e artículo está solución.',
 'Miembros llegó permite cierta ésta.',
 'Mayo política libro hacer algunos cualquier están.',
 'Enero esfuerzo mi luego estructura.',
 'Sangre marcha incluso gobierno nuevas autor.',
 'Architecto voluptatibus modi assumenda recusandae.',
 'Laudantium doloremque culpa.',
 'Doloremque ipsum neque optio dolore tempora totam.',
 'Ningún otros tipos volvió.',
 'Origen habla van internacional g padre.',
 'Plaza alguien mayor concepto control.',
 'Victoria jorge ve control barcelona ciento sol.',
 'Occaecati totam facere voluptate dicta.',
 'Respuesta s manuel elecciones.',
 'Pocos cierta estar muchas uso han personal.',
 'Respecto diversos parece precisamente acto capital su fútbol.',
 'Veniam optio nihil voluptatibus perspiciatis.',
 'Assumenda necessitatibus ratione pariatur natus itaque nemo hic.',
 'Omnis laboriosam voluptates quasi similique.',
 'Ipsum nulla tempore eius optio iste repellat ducimus.',
 'Dicta et eos explicabo fugiat tempore molestias numquam.',
 'Unas menor recuerdo tarde cine.',
 'Etapa distintos aun d conocer o millones.',
 'País trata voz nombre somos servicios hizo.',
 'Soluta at adipisci nulla nostrum a repudiandae doloremque.',
 'Volver cultura demás acerca han.',
 'Unos campaña otros decisión punto ir juan ministro.',
 'Presenta derecho allá pensar hermano.',
 'Mayoría pesetas recursos podemos pesetas.',
 'Hospital contrario miembros militares particular podía estuvo.',
 'Cierto argentina viaje francisco veces aquel capacidad.',
 'Electoral hijo falta segunda cuatro de pensar.',
 'Estructura así puerto superior días atención solo.',
 'Suscipit nesciunt libero facilis voluptas.',
 'Único principales comunidad silencio francisco propio cuenta.',
 'La ésta fuerzas negro.',
 'Puesto ex desarrollo señaló español características.',
 'Grupos cómo viene dónde j volver este decir.',
 'Hechos otro nueva arriba media.',
 'Quod corrupti optio enim deleniti.',
 'S supuesto pensar central animales hombre.',
 'Labore harum aperiam molestias quis sed.',
 'Fugiat at iure culpa facilis placeat.',
 'Calidad podrá san mar hasta.',
 'Difícil carácter don próximo.',
 'Ab reiciendis rem.',
 'Políticos pregunta ello me diversos ocho.',
 'Alias voluptas ducimus ratione iste quae magnam.',
 'Fernando medidas políticos cambio días principio.',
 'Voluptatem amet laboriosam vero ratione itaque.',
 'Puerta así gran estoy.',
 'Cumque possimus molestias placeat temporibus ut veniam.',
 'Economía necesario junto ellas juan.',
 'Siete animales hijos grado permite antes.',
 'Dicta impedit harum minus illo architecto.',
 'Ojos da técnica vuelta este.',
 'Deserunt repellat adipisci aliquam quidem adipisci eum voluptatem.',
 'Optio perferendis nemo.',
 'Informe difícil éxito cultural tengo relaciones salud dio.',
 'Numquam ipsam ut aspernatur.',
 'Laboriosam veritatis minima assumenda ad earum porro.',
 'Artículo tenía adelante entrada martín.',
 'Situación términos tales radio.',
 'Necesidad fueron desarrollo oficial.',
 'Quasi occaecati adipisci sit explicabo.',
 'Viene parte estas encuentro.',
 'Ideas civil reunión ambiente domingo peor.',
 'Tarde hicieron plaza muchos pesetas.',
 'Ducimus voluptatum assumenda commodi sint repellendus repellat.',
 'Fugiat quae voluptates.',
 'Origen nueva cuales.',
 'Ad iusto sint voluptas.',
 'Principal juan suelo pesetas.',
 'Cierta están sector ejército estudios unión.',
 'Poner nuevas sería nuestro río doctor.',
 'Eligendi animi consequuntur.',
 'Volver papel juan buscar como.',
 'Producto nunca humano.',
 'Odit ex hic itaque eos dolorum.',
 'Programas administración seguro miedo.',
 'Aliquid nemo tempore inventore repellat molestias ex.',
 'Facere sint quis dolorem provident asperiores veritatis.',
 'Cuatro alta idea conocimiento van él.',
 'Magnam id dignissimos quidem adipisci.',
 'Molestias cum a doloremque.',
 'Nueva corazón voy técnica toma.',
 'Noviembre duda pp voy blanco tienen.',
 'P que realidad dos nosotros estamos empresa recursos.',
 'Pueda poco luz algunas régimen corte da.',
 'Haber obras vía mayo idea elecciones seis lejos.',
 'Et neque deserunt dolorum necessitatibus ipsa.',
 'Aquella investigación i victoria española tan.',
 'Defensa jorge seis mañana.',
 'Encuentra opinión todo metros.',
 'Quia laborum dolore temporibus iste eum.',
 'Laborum quasi tempore voluptates eos recusandae ad.',
 'Autem fugit quo ullam.',
 'Busca superior tarde estaban.',
 'Ad odio quis laboriosam.',
 'Temporibus nulla nulla aliquid qui nesciunt.',
 'Región joven jamás relación lleva mirada debido martín.',
 'Eos dolores praesentium quis corrupti iste a.',
 'Doloribus modi saepe exercitationem repellat repudiandae.',
 'Función exterior unión da precios voy.',
 'Facere dicta qui modi officiis.',
 'Eum accusamus enim qui.',
 'Laboriosam accusantium excepturi magnam nobis.',
 'Eius est velit omnis quaerat nesciunt.',
 'Quae eveniet blanditiis quod.',
 'Incidunt ipsa perferendis.',
 'Ducimus illum distinctio a temporibus sunt porro.',
 'Quia repellendus quibusdam officiis atque magnam soluta laborum.',
 'Presente distintos cuatro contenido estados.',
 'Saber sector mismos quienes existencia conocer baja.',
 'Mollitia exercitationem quod minus perspiciatis.',
 'Quis vero suscipit.',

In [394]:
list(df['type'].unique())

['payment',
 'withdrawal',
 'comision',
 'fee',
 'refund',
 'Transfer',
 'deposit',
 'transfer',
 'FEE',
 'Deposito',
 'transferencia',
 'DEPOSIT',
 'WITHDRAWAL',
 'reembolso',
 'Deposit',
 'Refund',
 'Fee',
 'Pago',
 'pago',
 'Retiro',
 'Payment',
 'REFUND',
 'Comision',
 'Withdrawal',
 'PAYMENT',
 'deposito',
 'TRANSFER',
 'retiro']

In [387]:
list(df['date'].unique())

['2024-09-23',
 '2025-07-06',
 '2025-12-29',
 '2025-12-20',
 '2026-03-21',
 '06/02/2026',
 '2026-02-22',
 '20260226',
 '10/09/2024',
 '04-04-2026',
 '2025-11-23',
 '2026-04-23',
 '2024-01-22',
 '2025-04-04',
 '2026-02-10',
 '2024-04-28',
 '2026-04-15',
 '07-31-2022',
 '2025-07-21',
 '2025-06-16',
 '2026-02-28',
 '20251215',
 '2026-04-03',
 '2025-11-16',
 '2026-05-05',
 '2024-12-03',
 '2025-10-05',
 '2026-04-10',
 '2024-08-25',
 '01-26-2026',
 '20251227',
 '2024-08-03',
 '20251101',
 '08-10-2022',
 '2026-04-06',
 '2024-02-16',
 '2024-06-28',
 '2026-02-07',
 '2026-04-09',
 '20240809',
 '2025-09-12',
 '2025-10-22',
 '2026-01-14',
 '2025-03-14',
 '2026-02-11',
 '2025-05-25',
 '03/05/2026',
 '2025-03-07',
 '2025-10-09',
 '2025-12-19',
 '2026-05-03',
 '20260505',
 '2026-02-05',
 '2026-02-19',
 '2023-12-16',
 '19/04/2025',
 '20250213',
 '2025-11-11',
 '02-10-2026',
 '2026-04-28',
 '04-05-2026',
 '2026-03-08',
 '2025-11-10',
 '2026-01-10',
 '02-07-2026',
 '2025-07-15',
 '2026-04-20',
 '2024-04-17',
 '29/03/2026',
 '2023-12-20',
 '2026-04-08',
 '2024-03-07',
 '2026-02-18',
 '20260218',
 '2024-12-24',
 '2025-03-19',
 '2026-04-29',
 '03-23-2026',
 '2025-09-08',
 '2025-04-25',
 '2025-12-27',
 '2025-11-17',
 '2026-03-19',
 '2025-11-15',
 '2026-04-27',
 '2026-02-20',
 '2026-03-18',
 '2025-06-28',
 '2024-04-24',
 '2026-01-27',
 '2026-04-18',
 '05/10/2025',
 '12/04/2026',
 '31/03/2026',
 '2026-05-04',
 '2026-04-05',
 '19/03/2026',
 '2026-03-02',
 '2025-12-06',
 '20250919',
 '2025-10-23',
 '2026-03-23',
 '24/09/2025',
 '2026-05-01',
 '2025-06-03',
 '2025-08-04',
 '2026-04-21',
 '2026-03-13',
 '2026-04-24',
 '2024-11-10',
 '2026-04-12',
 '2024-06-16',
 '2025-07-13',
 '30/09/2023',
 '2025-11-25',
 '20250530',
 '04-18-2026',
 '2025-08-28',
 '2026-01-03',
 '2023-04-20',
 '2026-04-26',
 '20260403',
 '2026-03-25',
 '02-05-2026',
 '11-18-2024',
 '2025-12-24',
 '20260123',
 '01-03-2026',
 '05/12/2025',
 '2026-03-15',
 '2026-04-13',
 '2026-02-14',
 '2021-12-30',
 '2025-01-16',
 '2024-03-04',
 '2023-02-17',
 '2025-11-19',
 '2023-09-10',
 '11/02/2025',
 '2026-05-06',
 '12/02/2025',
 '20260409',
 '2026-03-16',
 '2026-03-30',
 '2025-05-31',
 '11-11-2025',
 '2026-04-17',
 '2026-02-12',
 '20/06/2023',
 '2025-11-29',
 '2023-01-16',
 '2026-05-02',
 '2025-09-07',
 '2022-05-27',
 '2026-03-24',
 '2024-02-10',
 '2025-04-30',
 '2024-10-27',
 '2023-10-18',
 '2024-01-10',
 '2025-08-30',
 '2024-03-24',
 '2025-12-16',
 '2026-04-22',
 '2025-10-17',
 '2024-07-16',
 '20250716',
 '2025-04-14',
 '2026-03-09',
 '20260320',
 '04/05/2024',
 '2025-11-27',
 '2025-12-05',
 '2025-09-28',
 '2024-10-16',
 '14/02/2026',
 '2026-01-24',
 '2026-01-12',
 '20250115',
 '11-14-2025',
 '2025-05-10',
 '2024-09-18',
 '2025-03-15',
 '11/11/2025',
 '2025-03-13',
 '2023-10-01',
 '11/12/2023',
 '2024-05-07',
 '2025-05-04',
 '2024-03-11',
 '27/01/2026',
 '2025-07-27',
 '2025-07-18',
 '2024-08-19',
 '11-04-2025',
 '2025-10-26',
 '2023-07-09',
 '2024-11-29',
 '2025-12-30',
 '2026-04-11',
 '2026-04-04',
 '2024-01-28',
 '2025-04-08',
 '2024-06-29',
 '2025-04-28',
 '2026-03-01',
 '2025-12-12',
 '2025-10-21',
 '05-04-2026',
 '2025-04-11',
 '2025-03-28',
 '2026-02-02',
 '2024-12-31',
 '2026-02-15',
 '2025-12-25',
 '2026-01-06',
 '2026-03-05',
 '2024-11-25',
 '05-18-2025',
 '2023-05-18',
 '2024-10-04',
 '2025-07-22',
 '2026-01-31',
 '2024-09-14',
 '2024-08-15',
 '2025-02-23',
 '2025-10-14',
 '2025-09-25',
 '2025-09-17',
 '20211014',
 '20/12/2025',
 '2026-02-27',
 '2026-02-25',
 '2025-06-10',
 '03-24-2026',
 '2025-07-09',
 '2025-08-03',
 '2026-02-01',
 '03-06-2024',
 '01-17-2026',
 '2026-04-14',
 '20251030',
 '04-08-2026',
 '2025-03-03',
 '2025-05-11',
 '2026-03-14',
 '06-23-2025',
 '2023-03-15',
 '2025-03-30',
 '2026-04-07',
 '2025-10-12',
 '2025-08-08',
 '2025-12-04',
 '2023-10-27',
 '2025-08-29',
 '2025-07-12',
 '04-29-2023',
 '2025-10-29',
 '2024-12-02',
 '2026-04-30',
 '2026-01-18',
 '2025-12-03',
 '2025-12-18',
 '2025-06-21',
 '2026-04-01',
 '20240701',
 '2025-11-09',
 '2025-06-04',
 '08/04/2026',
 '2026-01-17',
 '2025-02-15',
 '2026-02-06',
 '2024-02-25',
 '14/02/2025',
 '2026-03-06',
 '06/09/2024',
 '2025-08-14',
 '05-05-2026',
 '2026-01-01',
 '2026-03-28',
 '2024-11-11',
 '2025-06-20',
 '2024-06-12',
 '2024-05-10',
 '05-03-2026',
 '2025-07-19',
 '20251123',
 '2023-11-15',
 '2025-12-10',
 '2025-01-05',
 '2024-10-10',
 '01/05/2026',
 '2024-11-21',
 '2026-02-13',
 '2026-02-26',
 '20250209',
 '20260430',
 '2022-09-20',
 '04/10/2025',
 '04-02-2026',
 '2024-10-13',
 '20260211',
 '2025-07-31',
 '2025-11-02',
 '2021-05-05',
 '07-28-2025',
 '04-27-2026',
 '20231020',
 '2025-10-24',
 '2025-04-19',
 '2026-03-29',
 '2025-10-28',
 '09-29-2025',
 '20240811',
 '2025-08-06',
 '20250514',
 '2024-12-29',
 '2026-03-27',
 '2025-08-12',
 '26/11/2025',
 '27/08/2024',
 '18/07/2025',
 '2025-02-28',
 '2023-08-14',
 '2026-03-11',
 '20260414',
 '14/03/2026',
 '2025-10-03',
 '2024-05-23',
 '2024-06-15',
 '02/05/2026',
 '03-27-2026',
 '2026-01-15',
 '20250819',
 '2024-10-24',
 '2025-07-29',
 '2026-02-09',
 '2026-03-10',
 '2024-09-17',
 '2025-11-18',
 '2025-09-29',
 '20250216',
 '17/02/2024',
 '20250907',
 '2025-10-02',
 '2025-06-14',
 '2026-03-04',
 '20260424',
 '2026-01-13',
 '2025-04-01',
 '12-26-2024',
 '05/01/2026',
 '20250707',
 '2021-11-28',
 '2022-03-24',
 '20260417',
 '03-06-2023',
 '2025-10-11',
 '2026-01-20',
 '10-13-2024',
 '06-24-2025',
 '2025-06-09',
 '2026-02-23',
 '2025-10-16',
 '09-19-2025',
 '2025-09-10',
 '20260329',
 '09/04/2026',
 '2026-03-26',
 '18/09/2025',
 '20260426',
 '2023-07-12',
 '2026-04-16',
 '2026-03-12',
 '2025-03-27',
 '2025-06-05',
 '2026-03-22',
 '2023-10-25',
 '20251020',
 '2025-04-22',
 '2025-11-13',
 '2024-07-17',
 '20250823',
 '2025-12-21',
 '20260425',
 '2025-08-21',
 '04/08/2024',
 '2024-04-20',
 '05-11-2024',
 '2025-07-30',
 '20260301',
 '20250719',
 '03-13-2025',
 '04-23-2026',
 '04/05/2026',
 '2025-05-20',
 '06-22-2025',
 '14/07/2025',
 '2025-07-02',
 '2025-09-27',
 '05/05/2026',
 '04-21-2026',
 '15/02/2026',
 '2025-06-24',
 '12-25-2021',
 '2024-08-23',
 '2024-09-16',
 '2024-06-09',
 '06-14-2025',
 '2026-04-25',
 '03-22-2024',
 '2025-08-16',
 '2025-11-12',
 '2024-03-01',
 '2025-10-07',
 '19/07/2025',
 '2025-07-01',
 '02/11/2025',
 '2025-08-24',
 '2022-11-21',
 '2024-10-29',
 '20251108',
 '2025-09-23',
 '2026-02-21',
 '20240502',
 '2025-12-22',
 '2024-04-30',
 '03-10-2026',
 '2025-10-30',
 '2025-08-31',
 '2025-05-08',
 '05-06-2026',
 '2025-06-30',
 '20260306',
 '20251226',
 '05-12-2025',
 '30/05/2025',
 '2023-06-06',
 '2026-01-21',
 '2026-01-09',
 '2025-09-14',
 '2024-07-05',
 '2025-11-26',
 '2025-09-30',
 '2024-08-18',
 '2024-05-21',
 '2024-08-28',
 '2024-09-24',
 '09/08/2022',
 '2025-03-22',
 '2026-02-24',
 '2025-11-21',
 '2024-09-10',
 '2024-07-08',
 '2024-11-24',
 '2025-11-08',
 '2025-08-13',
 '2026-01-30',
 '20240604',
 '08-05-2025',
 '2026-01-22',
 '2025-02-11',
 '2025-05-06',
 '2025-01-14',
 '2025-06-23',
 '20230704',
 '2024-04-08',
 '2025-04-21',
 '20230623',
 '2024-02-26',
 '2024-10-09',
 '2023-09-28',
 '2026-03-07',
 '04-15-2025',
 '20251220',
 '2025-09-02',
 '23/06/2025',
 '2025-02-26',
 '2025-09-01',
 '2025-08-19',
 '2021-09-29',
 '28/03/2026',
 '2025-01-22',
 '20260328',
 '03/03/2024',
 '2025-10-18',
 '01-01-2026',
 '2023-06-04',
 '2023-01-18',
 '12-11-2025',
 '20251219',
 '2025-03-09',
 '2026-04-02',
 '2022-04-09',
 '12-08-2023',
 '11/11/2024',
 '2023-02-25',
 '2025-03-23',
 '20240909',
 '2024-11-30',
 '2023-12-28',
 '2023-02-21',
 '2025-09-09',
 '2025-10-10',
 '2026-01-23',
 '22/08/2025',
 '2023-10-22',
 '2026-03-20',
 '2024-08-11',
 '2024-10-18',
 '25/09/2025',
 '2025-11-03',
 '2025-07-14',
 '2025-12-07',
 '2025-04-12',
 '2025-12-09',
 '22/12/2024',
 '2025-03-12',
 '2025-04-29',
 '2026-01-26',
 '20250505',
 '2023-04-01',
 '2025-03-10',
 '2026-01-05',
 '2025-05-30',
 '2025-01-02',
 '2024-09-02',
 '2025-04-13',
 '04-28-2026',
 '2025-09-03',
 '2025-05-01',
 '09/12/2025',
 '2025-08-26',
 '31/01/2025',
 '2022-08-24',
 '11/12/2025',
 '2024-10-19',
 '2024-09-26',
 '09/09/2021',
 '2024-09-15',
 '05-15-2025',
 '02-12-2024',
 '20250831',
 '18/04/2026',
 '2021-05-13',
 '07/01/2026',
 '2026-01-04',
 '2025-10-13',
 '29/04/2026',
 '2025-06-07',
 '2026-01-19',
 '2024-09-08',
 '2023-09-23',
 '12/01/2026',
 '20240923',
 '15/04/2026',
 '2025-09-26',
 '02-20-2026',
 '20260410',
 '20241030',
 '11-18-2025',
 '12/03/2026',
 '2025-09-19',
 '20251006',
 '2025-11-04',
 '2025-09-22',
 '2023-08-31',
 '01/04/2026',
 '2025-11-24',
 '2026-03-31',
 '2025-11-05',
 '10-13-2025',
 '2025-08-10',
 '2025-10-15',
 '2025-07-04',
 '20251217',
 '01-23-2026',
 '04-06-2026',
 '22/02/2025',
 '28/09/2025',
 '2022-02-17',
 '2025-06-13',
 '2024-05-18',
 '2023-03-02',
 '20250726',
 '10/03/2026',
 '2025-12-11',
 '03-28-2026',
 '20260408',
 '2025-05-14',
 '2026-03-03',
 '2025-03-05',
 '2024-07-24',
 '2024-04-06',
 '2023-12-21',
 '2024-12-09',
 '09-01-2025',
 '2024-09-05',
 '2025-07-16',
 '2026-01-07',
 '2025-01-04',
 '2026-01-16',
 '2026-01-25',
 '2025-07-23',
 '02-18-2026',
 '2026-04-19',
 '2024-02-22',
 '2021-08-18',
 '2024-10-12',
 '09-22-2023',
 '2025-06-29',
 '11-03-2025',
 '04-07-2026',
 '2025-02-10',
 '2025-11-14',
 '2024-12-27',
 '2025-06-12',
 '2022-10-26',
 '2025-05-03',
 '2026-01-08',
 '24/01/2026',
 '20260402',
 '23/03/2026',
 '2025-12-08',
 '10/12/2025',
 '2025-12-15',
 '07/07/2024',
 '2025-05-23',
 '26/03/2026',
 '2025-10-25',
 '18/11/2025',
 '20250110',
 '20260428',
 '2024-10-14',
 '09-07-2025',
 '2025-06-27',
 '2026-01-29',
 '16/02/2025',
 '10-25-2024',
 '2025-10-20',
 '2025-01-01',
 '2025-02-05',
 '2024-06-20',
 '16/04/2024',
 '2024-11-08',
 '05/02/2026',
 '2022-08-05',
 '04-13-2026',
 '2024-11-26',
 '2024-11-02',
 '2024-02-23',
 '2026-01-28',
 '22/10/2025',
 '20250927',
 '2025-07-08',
 '20260502',
 '21/10/2025',
 '08-13-2021',
 '2025-01-15',
 '2025-10-04',
 '2024-03-19',
 '26/02/2023',
 '2025-05-19',
 '02-17-2026',
 '2025-04-03',
 '20250429',
 '20260310',
 '2025-12-13',
 '08-01-2025',
 '07/08/2025',
 '2023-12-04',
 '26/02/2026',
 '2024-11-15',
 '2025-11-06',
 '2025-06-19',
 '2025-05-09',
 '23/08/2024',
 '05-04-2025',
 '20250817',
 '2026-03-17',
 '20240710',
 '2025-01-31',
 '2025-06-06',
 '2024-04-10',
 '16/11/2025',
 '2025-12-14',
 '2025-07-05',
 '2025-01-09',
 '11-19-2024',
 '2023-09-21',
 '05/11/2023',
 '20250522',
 '2024-10-28',
 '2023-02-26',
 '2024-12-05',
 '2025-08-15',
 '2025-02-19',
 '2025-03-20',
 '2025-12-02',
 '20260314',
 '03-27-2025',
 '2024-12-23',
 '20260316',
 '20260309',
 '2025-08-05',
 '01/03/2026',
 '04/12/2025',
 '20260128',
 '2025-02-18',
 '20260404',
 '2023-01-21',
 '2024-01-24',
 '2024-07-14',
 '12-02-2024',
 '20251022',
 '2023-12-17',
 '24/02/2026',
 '2026-01-11',
 '20240518',
 '2024-06-17',
 '2022-01-16',
 '20230731',
 '20250525',
 '2024-10-07',
 '2025-08-07',
 '2025-04-05',
 '2023-08-12',
 '2025-03-11',
 '2025-10-19',
 '2025-06-11',
 '2024-12-11',
 '2025-07-24',
 '06/12/2025',
 '06/12/2024',
 '09-25-2025',
 '2024-12-25',
 '2023-02-03',
 '2025-01-27',
 '2022-09-16',
 '2025-08-23',
 '20251212',
 '04-24-2026',
 '06-08-2024',
 '19/06/2024',
 '2025-05-26',
 '2025-08-11',
 '2024-03-03',
 '04/08/2022',
 '2024-11-14',
 '2023-08-05',
 '06-11-2025',
 '13/04/2026',
 '20260327',
 '2023-06-26',
 '2023-12-31',
 '20260204',
 '11-17-2025',
 '11-17-2021',
 '2024-06-05',
 '2025-06-26',
 '2025-09-16',
 '09-19-2023',
 '2024-06-27',
 '2023-01-14',
 '31/01/2026',
 '20260401',
 '30/08/2024',
 '2022-09-09',
 '01-28-2026',
 '20250620',
 '2024-01-09',
 '2023-12-09',
 '05/03/2026',
 '2025-03-17',
 '2023-02-19',
 '2025-05-17',
 '2025-09-24',
 '2023-12-02',
 '06-04-2024',
 '2023-07-30',
 '04-26-2026',
 '10/12/2023',
 '2026-02-04',
 '01-02-2026',
 '2025-05-22',
 '2023-10-04',
 '2025-01-06',
 '04-09-2026',
 '12-20-2025',
 '12-10-2025',
 '2025-04-15',
 '2024-12-16',
 '2023-10-08',
 '2025-05-15',
 '17/02/2026',
 '20260322',
 '2025-09-20',
 '2025-08-25',
 '2022-02-18',
 '20250120',
 '07/06/2023',
 '2025-05-18',
 '04-16-2025',
 '2025-11-28',
 '20260130',
 '2024-02-07',
 '2025-08-01',
 '2024-07-11',
 '2024-08-24',
 '2025-02-01',
 '2025-12-31',
 '20251130',
 '2023-12-05',
 '20260127',
 '20251127',
 '2023-03-17',
 '2023-08-30',
 '2023-11-06',
 '2025-10-27',
 '05-16-2025',
 '2025-05-24',
 '2023-07-25',
 '2024-11-01',
 '2024-10-30',
 '2026-01-02',
 '2025-10-01',
 '2023-10-31',
 '20250909',
 '2025-01-03',
 '12-01-2025',
 '20260118',
 '2024-03-18',
 '2025-12-26',
 '2025-10-08',
 '2025-10-31',
 '2024-11-05',
 '20251206',
 '16/08/2024',
 '20251015',
 '2025-04-20',
 '2021-04-18',
 '20260330',
 '2021-12-25',
 '23/01/2026',
 '30/01/2026',
 '20260222',
 '2025-11-07',
 '2024-05-05',
 '2024-03-10',
 '2022-08-15',
 '2026-02-08',
 '01-24-2025',
 '20260308',
 '2024-09-09',
 '2023-01-05',
 '2024-12-28',
 '2024-06-06',
 '2024-09-20',
 '2024-09-07',
 '2021-06-24',
 '2024-02-20',
 '20240927',
 '2023-09-12',
 '20240816',
 '2024-04-23',
 '2025-12-28',
 '2025-10-06',
 '2025-09-13',
 '2024-11-03',
 '2023-10-17',
 '2025-06-15',
 '2026-02-16',
 '20241028',
 '2025-08-18',
 '2021-09-22',
 '17/11/2025',
 '2025-12-01',
 '2024-07-02',
 '2023-06-21',
 '2023-06-05',
 '2023-07-13',
 '09-18-2025',
 '2026-02-17',
 '15/05/2024',
 '2022-03-23',
 '2025-05-07',
 '28/11/2025',
 '2024-07-23',
 '2022-07-11',
 '08-26-2025',
 '2024-08-16',
 '2022-12-08',
 '20241007',
 '12-20-2024',
 '09-03-2024',
 '11/04/2026',
 '2025-07-11',
 '2022-03-26',
 '20250822',
 '06-09-2024',
 '07-14-2024',
 '20240517',
 '20220303',
 '09/02/2026',
 '01/08/2025',
 '2024-12-12',
 '17/12/2025',
 '2024-06-22',
 '2024-03-17',
 '30/04/2026',
 '2025-06-18',
 '11-07-2025',
 '18/12/2025',
 '08-15-2022',
 '12-04-2024',
 '2024-01-18',
 '01-20-2026',
 '2025-05-21',
 '17/03/2025',
 '2023-10-03',
 '2025-07-17',
 '06/05/2026',
 '2025-03-04',
 '2024-06-23',
 '2025-09-06',
 '2024-07-04',
 '20260219',
 '05-09-2025',
 '2024-12-07',
 '2023-12-13',
 '05/12/2024',
 '20260501',
 '2025-08-27',
 '2022-03-10',
 '2024-07-12',
 '07-22-2023',
 '20251218',
 '2024-09-11',
 '20250228',
 '2023-12-24',
 '2025-08-09',
 '2024-11-28',
 '2025-08-20',
 '10/06/2024',
 '2024-10-03',
 '2021-11-17',
 '2024-05-02',
 '2025-11-20',
 '2024-11-20',
 '2023-12-22',
 '12-28-2025',
 '2025-08-22',
 '26/09/2025',
 '20260504',
 '03/12/2025',
 '20/03/2026',
 '20260323',
 '20251228',
 '2025-05-13',
 '2025-11-01',
 '20211018',
 '2025-09-15',
 '2025-03-01',
 '16/04/2026',
 '20260419',
 '2021-05-02',
 '20241029',
 '2024-06-24',
 '2025-08-02',
 '20241224',
 '03/04/2024',
 '20260506',
 '20250906',
 '03-09-2026',
 '2023-07-31',
 '14/04/2026',
 '2023-05-29',
 '23/09/2025',
 '03-25-2026',
 '2025-07-28',
 '20211026',
 '2024-02-11',
 '09-10-2025',
 '09-21-2023',
 '2024-02-29',
 '2024-12-10',
 '2024-09-21',
 '02-01-2026',
 '09/09/2024',
 '02/04/2026',
 '2023-03-28',
 '02-03-2024',
 '2023-06-01',
 '2023-05-19',
 '20260115',
 '20251202',
 '2024-04-02',
 '2025-07-10',
 '01-29-2026',
 '21/01/2026',
 ...]

In [345]:
import pandas as pd

def no_convertible_a_entero(serie: pd.Series) -> pd.Series:
    """
    Recibe una serie de pandas y retorna una serie con los valores únicos
    que NO se pueden convertir a números flotantes.
    """
    # 1. Intentamos la conversión. Los errores se convierten en NaN
    conversion = pd.to_numeric(serie, errors='coerce')
    
    # 2. Filtramos la serie original donde la conversión falló (es NaN)
    # y usamos .unique() para no repetir los mismos errores
    valores_invalidos = serie[conversion.isna()].unique()
    
    return valores_invalidos

In [344]:
df.isna().sum()

customer_id                0
mobile_app_registered      0
web_banking_registered     0
last_login_date            0
avg_monthly_logins        68
preferred_channel          0
push_notifications         0
paperless_statements       0
dtype: int64

## mobile_app_registered

In [340]:
df['mobile_app_registered'].unique()

array([False,  True])

## web_banking_registered

In [341]:
df['web_banking_registered'].unique()

array([ True, False])

## last_login_date

In [342]:
list(df['last_login_date'].unique())

[datetime.date(2025, 10, 23),
 datetime.date(2025, 11, 9),
 datetime.date(2026, 4, 1),
 datetime.date(2025, 8, 20),
 datetime.date(2025, 9, 9),
 datetime.date(2025, 9, 23),
 datetime.date(2025, 10, 28),
 datetime.date(2025, 8, 29),
 datetime.date(2025, 9, 13),
 datetime.date(2025, 10, 27),
 datetime.date(2026, 1, 29),
 datetime.date(2025, 11, 13),
 datetime.date(2026, 1, 11),
 datetime.date(2025, 9, 6),
 datetime.date(2026, 2, 25),
 datetime.date(2026, 1, 9),
 datetime.date(2025, 5, 25),
 datetime.date(2026, 3, 6),
 datetime.date(2026, 1, 2),
 datetime.date(2025, 6, 20),
 datetime.date(2026, 3, 18),
 datetime.date(2025, 7, 20),
 datetime.date(2025, 12, 8),
 datetime.date(2025, 5, 22),
 datetime.date(2025, 8, 24),
 datetime.date(2025, 9, 18),
 datetime.date(2025, 10, 22),
 datetime.date(2025, 12, 29),
 datetime.date(2025, 6, 26),
 datetime.date(2026, 3, 11),
 datetime.date(2026, 4, 10),
 datetime.date(2025, 5, 13),
 datetime.date(2025, 8, 7),
 datetime.date(2025, 7, 14),
 datetime.date(2026, 3, 30),
 datetime.date(2026, 3, 28),
 datetime.date(2026, 3, 24),
 datetime.date(2025, 7, 2),
 datetime.date(2025, 5, 19),
 datetime.date(2025, 9, 17),
 datetime.date(2025, 7, 22),
 datetime.date(2025, 5, 10),
 datetime.date(2025, 7, 13),
 datetime.date(2025, 12, 10),
 datetime.date(2026, 4, 25),
 datetime.date(2025, 7, 18),
 datetime.date(2025, 10, 6),
 datetime.date(2025, 5, 16),
 datetime.date(2026, 3, 31),
 datetime.date(2025, 12, 6),
 datetime.date(2025, 6, 23),
 datetime.date(2025, 5, 14),
 datetime.date(2025, 6, 21),
 datetime.date(2025, 10, 11),
 datetime.date(2025, 9, 19),
 datetime.date(2025, 11, 25),
 datetime.date(2025, 6, 9),
 datetime.date(2026, 2, 27),
 datetime.date(2026, 3, 17),
 datetime.date(2026, 5, 1),
 datetime.date(2025, 8, 11),
 datetime.date(2025, 12, 19),
 datetime.date(2025, 7, 26),
 datetime.date(2025, 11, 30),
 datetime.date(2025, 8, 23),
 datetime.date(2025, 12, 30),
 datetime.date(2026, 5, 5),
 datetime.date(2025, 6, 29),
 datetime.date(2025, 7, 29),
 datetime.date(2025, 9, 20),
 datetime.date(2025, 10, 25),
 datetime.date(2025, 5, 8),
 datetime.date(2025, 8, 26),
 datetime.date(2025, 12, 23),
 datetime.date(2025, 11, 22),
 datetime.date(2025, 10, 1),
 datetime.date(2026, 1, 25),
 datetime.date(2025, 6, 10),
 datetime.date(2026, 4, 5),
 datetime.date(2026, 2, 12),
 datetime.date(2025, 8, 15),
 datetime.date(2026, 2, 2),
 datetime.date(2025, 11, 4),
 datetime.date(2026, 3, 8),
 datetime.date(2026, 2, 20),
 datetime.date(2025, 8, 19),
 datetime.date(2025, 9, 21),
 datetime.date(2026, 4, 6),
 datetime.date(2026, 3, 4),
 datetime.date(2026, 2, 24),
 datetime.date(2025, 5, 15),
 datetime.date(2026, 1, 26),
 datetime.date(2025, 6, 3),
 datetime.date(2026, 1, 23),
 datetime.date(2025, 6, 22),
 datetime.date(2026, 4, 12),
 datetime.date(2025, 11, 18),
 datetime.date(2025, 12, 25),
 datetime.date(2026, 4, 30),
 datetime.date(2025, 9, 10),
 datetime.date(2025, 12, 24),
 datetime.date(2025, 5, 12),
 datetime.date(2026, 3, 19),
 datetime.date(2025, 8, 30),
 datetime.date(2026, 1, 12),
 datetime.date(2026, 2, 19),
 datetime.date(2026, 2, 11),
 datetime.date(2026, 4, 19),
 datetime.date(2026, 2, 15),
 datetime.date(2025, 7, 21),
 datetime.date(2025, 6, 11),
 datetime.date(2026, 1, 31),
 datetime.date(2025, 11, 15),
 datetime.date(2025, 12, 18),
 datetime.date(2026, 1, 16),
 datetime.date(2025, 10, 19),
 datetime.date(2026, 4, 15),
 datetime.date(2025, 10, 21),
 datetime.date(2025, 8, 22),
 datetime.date(2025, 9, 15),
 datetime.date(2025, 8, 13),
 datetime.date(2026, 1, 10),
 datetime.date(2026, 2, 18),
 datetime.date(2026, 2, 8),
 datetime.date(2026, 1, 28),
 datetime.date(2025, 7, 10),
 datetime.date(2025, 9, 11),
 datetime.date(2025, 6, 28),
 datetime.date(2026, 2, 26),
 datetime.date(2025, 5, 9),
 datetime.date(2025, 11, 29),
 datetime.date(2025, 6, 4),
 datetime.date(2026, 2, 9),
 datetime.date(2026, 1, 3),
 datetime.date(2025, 12, 1),
 datetime.date(2025, 10, 4),
 datetime.date(2025, 9, 30),
 datetime.date(2026, 2, 28),
 datetime.date(2026, 4, 16),
 datetime.date(2025, 8, 14),
 datetime.date(2025, 5, 6),
 datetime.date(2025, 11, 26),
 datetime.date(2025, 10, 31),
 datetime.date(2025, 10, 14),
 datetime.date(2025, 6, 17),
 datetime.date(2025, 10, 13),
 datetime.date(2026, 4, 23),
 datetime.date(2026, 2, 7),
 datetime.date(2025, 8, 31),
 datetime.date(2025, 9, 16),
 datetime.date(2025, 7, 23),
 datetime.date(2025, 6, 13),
 datetime.date(2025, 11, 7),
 datetime.date(2025, 7, 11),
 datetime.date(2025, 5, 28),
 datetime.date(2025, 9, 8),
 datetime.date(2026, 5, 4),
 datetime.date(2026, 4, 4),
 datetime.date(2026, 4, 26),
 datetime.date(2025, 10, 17),
 datetime.date(2025, 8, 27),
 datetime.date(2026, 4, 21),
 datetime.date(2025, 7, 7),
 datetime.date(2025, 11, 20),
 datetime.date(2025, 5, 29),
 datetime.date(2025, 8, 18),
 datetime.date(2025, 6, 15),
 datetime.date(2025, 11, 2),
 datetime.date(2025, 11, 21),
 datetime.date(2025, 7, 17),
 datetime.date(2025, 11, 8),
 datetime.date(2025, 8, 3),
 datetime.date(2025, 10, 26),
 datetime.date(2025, 10, 16),
 datetime.date(2026, 1, 19),
 datetime.date(2025, 6, 8),
 datetime.date(2025, 7, 30),
 datetime.date(2026, 3, 1),
 datetime.date(2026, 3, 21),
 datetime.date(2026, 3, 23),
 datetime.date(2026, 1, 5),
 datetime.date(2025, 6, 18),
 datetime.date(2025, 5, 26),
 datetime.date(2025, 5, 18),
 datetime.date(2026, 1, 15),
 datetime.date(2025, 7, 24),
 datetime.date(2025, 7, 5),
 datetime.date(2025, 10, 30),
 datetime.date(2026, 1, 21),
 datetime.date(2025, 6, 27),
 datetime.date(2025, 6, 24),
 datetime.date(2025, 12, 3),
 datetime.date(2026, 4, 2),
 datetime.date(2025, 10, 9),
 datetime.date(2026, 5, 6),
 datetime.date(2025, 11, 23),
 datetime.date(2026, 2, 4),
 datetime.date(2026, 4, 20),
 datetime.date(2025, 6, 25),
 datetime.date(2026, 2, 21),
 datetime.date(2026, 3, 13),
 datetime.date(2025, 11, 1),
 datetime.date(2025, 12, 20),
 datetime.date(2026, 2, 23),
 datetime.date(2025, 9, 26),
 datetime.date(2026, 3, 29),
 datetime.date(2026, 3, 12),
 datetime.date(2026, 2, 6),
 datetime.date(2025, 10, 8),
 datetime.date(2025, 9, 5),
 datetime.date(2026, 2, 3),
 datetime.date(2025, 8, 10),
 datetime.date(2025, 11, 19),
 datetime.date(2026, 4, 18),
 datetime.date(2025, 6, 5),
 datetime.date(2025, 11, 16),
 datetime.date(2026, 3, 15),
 datetime.date(2025, 11, 11),
 datetime.date(2025, 8, 28),
 datetime.date(2025, 7, 4),
 datetime.date(2025, 7, 28),
 datetime.date(2025, 11, 28),
 datetime.date(2026, 2, 17),
 datetime.date(2026, 1, 24),
 datetime.date(2025, 11, 17),
 datetime.date(2026, 1, 6),
 datetime.date(2025, 12, 21),
 datetime.date(2026, 4, 14),
 datetime.date(2025, 5, 21),
 datetime.date(2025, 6, 7),
 datetime.date(2025, 8, 9),
 datetime.date(2025, 9, 1),
 datetime.date(2026, 3, 16),
 datetime.date(2025, 11, 10),
 datetime.date(2025, 12, 2),
 datetime.date(2026, 2, 10),
 datetime.date(2026, 1, 18),
 datetime.date(2026, 1, 4),
 datetime.date(2026, 4, 29),
 datetime.date(2025, 12, 7),
 datetime.date(2025, 11, 6),
 datetime.date(2025, 8, 2),
 datetime.date(2025, 11, 24),
 datetime.date(2026, 5, 2),
 datetime.date(2025, 11, 14),
 datetime.date(2026, 1, 14),
 datetime.date(2026, 1, 1),
 datetime.date(2025, 8, 21),
 datetime.date(2026, 5, 3),
 datetime.date(2025, 8, 4),
 datetime.date(2025, 10, 12),
 datetime.date(2025, 5, 24),
 datetime.date(2025, 10, 3),
 datetime.date(2025, 12, 14),
 datetime.date(2025, 7, 27),
 datetime.date(2025, 5, 23),
 datetime.date(2026, 3, 25),
 datetime.date(2026, 3, 10),
 datetime.date(2025, 12, 13),
 datetime.date(2026, 4, 28),
 datetime.date(2025, 9, 22),
 datetime.date(2025, 8, 8),
 datetime.date(2026, 3, 20),
 datetime.date(2025, 12, 9),
 datetime.date(2025, 9, 4),
 datetime.date(2026, 3, 5),
 datetime.date(2025, 7, 12),
 datetime.date(2025, 12, 28),
 datetime.date(2025, 12, 5),
 datetime.date(2025, 6, 12),
 datetime.date(2025, 5, 17),
 datetime.date(2026, 3, 3),
 datetime.date(2026, 4, 3),
 datetime.date(2025, 9, 14),
 datetime.date(2025, 7, 31),
 datetime.date(2025, 8, 6),
 datetime.date(2025, 7, 25),
 datetime.date(2025, 8, 17),
 datetime.date(2025, 12, 26),
 datetime.date(2026, 2, 13),
 datetime.date(2025, 7, 19),
 datetime.date(2025, 12, 16),
 datetime.date(2026, 4, 22),
 datetime.date(2025, 9, 12),
 datetime.date(2025, 12, 31),
 datetime.date(2026, 3, 2),
 datetime.date(2025, 8, 25),
 datetime.date(2025, 9, 29),
 datetime.date(2025, 7, 1),
 datetime.date(2026, 2, 22),
 datetime.date(2025, 7, 8),
 datetime.date(2026, 1, 7),
 datetime.date(2026, 1, 30),
 datetime.date(2025, 9, 2),
 datetime.date(2026, 4, 27),
 datetime.date(2025, 10, 10),
 datetime.date(2026, 3, 22),
 datetime.date(2026, 3, 26),
 datetime.date(2025, 12, 11),
 datetime.date(2025, 12, 27),
 datetime.date(2025, 8, 16),
 datetime.date(2025, 6, 16),
 datetime.date(2025, 5, 7),
 datetime.date(2026, 1, 27),
 datetime.date(2025, 6, 2),
 datetime.date(2025, 6, 19),
 datetime.date(2025, 10, 20),
 datetime.date(2026, 1, 17),
 datetime.date(2026, 2, 16),
 datetime.date(2026, 4, 8),
 datetime.date(2025, 12, 22),
 datetime.date(2025, 12, 15),
 datetime.date(2025, 8, 5),
 datetime.date(2025, 7, 9),
 datetime.date(2025, 10, 24),
 datetime.date(2025, 9, 25),
 datetime.date(2026, 4, 7),
 datetime.date(2025, 11, 5),
 datetime.date(2025, 11, 3),
 datetime.date(2026, 1, 20),
 datetime.date(2025, 7, 16),
 datetime.date(2026, 2, 5),
 datetime.date(2025, 9, 3),
 datetime.date(2025, 12, 4),
 datetime.date(2025, 10, 15),
 datetime.date(2025, 10, 29),
 datetime.date(2025, 5, 31),
 datetime.date(2025, 7, 15),
 datetime.date(2025, 10, 7),
 datetime.date(2025, 9, 28),
 datetime.date(2025, 5, 30),
 datetime.date(2026, 4, 11),
 datetime.date(2026, 4, 17),
 datetime.date(2026, 1, 22),
 datetime.date(2026, 4, 13),
 datetime.date(2025, 10, 5),
 datetime.date(2025, 10, 18),
 datetime.date(2025, 11, 27),
 datetime.date(2026, 3, 9),
 datetime.date(2025, 12, 12),
 datetime.date(2026, 3, 27),
 datetime.date(2025, 9, 24),
 datetime.date(2025, 6, 30),
 datetime.date(2026, 4, 9),
 datetime.date(2025, 8, 12),
 datetime.date(2026, 2, 1),
 datetime.date(2025, 6, 14),
 datetime.date(2026, 3, 14),
 datetime.date(2026, 2, 14),
 datetime.date(2025, 6, 6),
 datetime.date(2025, 9, 27),
 datetime.date(2026, 3, 7),
 datetime.date(2025, 12, 17),
 datetime.date(2025, 7, 3),
 datetime.date(2025, 5, 20),
 datetime.date(2025, 5, 11),
 datetime.date(2025, 10, 2),
 datetime.date(2025, 6, 1),
 datetime.date(2026, 1, 8),
 datetime.date(2026, 4, 24),
 datetime.date(2025, 9, 7),
 datetime.date(2025, 8, 1),
 datetime.date(2025, 5, 27),
 datetime.date(2025, 7, 6),
 datetime.date(2025, 11, 12),
 datetime.date(2026, 1, 13)]

## avg_monthly_logins

In [349]:
no_convertible_a_entero(df['avg_monthly_logins'])

<ArrowStringArray>
['', 'N/A', 'NA', 'null', nan]
Length: 5, dtype: str

## preferred_channel

In [351]:
df['preferred_channel'].unique()

<ArrowStringArray>
['web', 'mobile', 'branch', 'atm', 'phone']
Length: 5, dtype: str

## push_notifications

In [353]:
df['push_notifications'].unique()

<ArrowStringArray>
['true', 'false', 'no', 'yes', '1', '0']
Length: 6, dtype: str

## paperless_statements

In [355]:
df['paperless_statements'].unique()

<ArrowStringArray>
['true', 'false', 'no', '1', '0', 'si']
Length: 6, dtype: str

# Age calculation

In [39]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')
tables = ['silver.credit_info','silver.digital_engagement','silver.stg_customers']
# Write query to get date, tmax, and tmin from weather
query = f"""
select *
from silver.stg_customers
"""

# Make a dataframe by passing query and engine to read_sql()
df = pd.read_sql(query,engine)

In [40]:
import json
import pandas as pd

# 1. Convert the JSON strings into Python dictionaries
# (We use errors='ignore' or a lambda to handle potential malformed strings safely)
dicts = df["credit_info"].apply(json.loads)

# 2. Flatten those dictionaries into a clean, new DataFrame
df_clean = pd.json_normalize(dicts)

# 3. Join it back to your original DataFrame if you need to keep other columns
df = df.join(df_clean)

In [60]:
df_clean['utilization_pct'].unique()

<StringArray>
[ '56.13',  '59.99',  '10.18',  '38.54', '$19.28',  '69.95',  '76.26',
  '68.47',  '47.02',  '22.04',
 ...
  '59.21',  '67.85',  '82.71',  '61.83',  '63.88',  '26.42',  '56.59',
  '51.54',   '4.37',  '23.45']
Length: 3966, dtype: str

In [ ]:
"SELECT DISTINCT preferred_channel FROM silver.digital_engagement

In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Create database engine for data.db
engine = create_engine('postgresql://qversity-admin:qversity-admin@localhost:5432/qversity')
# Write query to get date, tmax, and tmin from weather
query = f"""
select *
from silver.digital_engagement
"""

# Make a dataframe by passing query and engine to read_sql()
base = pd.read_sql(query,engine)

In [2]:
df = base

In [6]:
df['preferred_channel'].unique()

<StringArray>
['atm', 'branch', 'mobile', 'phone', 'web']
Length: 5, dtype: str

In [57]:
base['date_of_birth'].max()

datetime.date(2008, 5, 6)